
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT 
TRAJECT_DTCMEDIA_CRM_ID,
TRAJECT_TRAJECTID,
MAX(IF(rank = 1, OFFERTE_OFFERTEID, null)) as unieke_getekende_offerte,
MAX(IF(TRAJECTSTATUSID = "2", OFFERTE_OFFERTEID, null)) as unieke_getekende_overeenkomst,
COUNT(DISTINCT(NULLIF(TRIM(OFFERTE_OFFERTEID), ""))) AS getekende_offertes,
MAX(IF(rank = 1, OFFERTESTATUS_OMSCHRIJVING, null)) as OFFERTESTATUS_OMSCHRIJVING,
MAX(IF(rank = 1, OFFERTE_DATUMOFFERTE, null)) as OFFERTE_DATUMOFFERTE,
MAX(IF(rank = 1, OFFERTE_TOTAALBEDRAG, null)) as OFFERTE_TOTAALBEDRAG,
MAX(IF(rank = 1, AUTOPRIJSCONSUMENT, null)) as AUTOPRIJSCONSUMENT,
MAX(IF(rank = 1, NETTOCATPRIJS, null)) as NETTOCATPRIJS,
MAX(IF(rank = 1, OFFERTEVTR_TRANSACTIERESULTAAT, null)) as OFFERTEVTR_TRANSACTIERESULTAAT,
MAX(IF(rank = 1, OFFERTEVTR_BRUTOMARGEBEDRAG, null)) as OFFERTEVTR_BRUTOMARGEBEDRAG,
MAX(IF(rank = 1, AFLEVERINGMODEL_OMSCHRIJVING, null)) as AFLEVERINGMODEL_OMSCHRIJVING,
MAX(IF(rank = 1, MERK_OMSCHRIJVING, null)) as MERK_OMSCHRIJVING,
MAX(IF(rank = 1, OCCASION_KENTEKEN, null)) as OCCASION_KENTEKEN,
MAX(IF(rank = 1, OCCASION_KILOMETERSTAND, null)) as OCCASION_KILOMETERSTAND,
MAX(IF(rank = 1, OCCASION_DATUMDEEL1, null)) as OCCASION_DATUMDEEL1,
MAX(IF(rank = 1, INRUILOCCASION_KENTEKEN, null)) as INRUILOCCASION_KENTEKEN,
MAX(IF(rank = 1, INRUILOCCASION_MERKNAAM, null)) as INRUILOCCASION_MERKNAAM,
MAX(IF(rank = 1, INRUILOCCASION_MODELNAAM, null)) as INRUILOCCASION_MODELNAAM

FROM(
  SELECT 
*,
ROW_NUMBER() OVER(PARTITION BY TRAJECT_DTCMEDIA_CRM_ID, TRAJECT_TRAJECTID ORDER BY OFFERTE_DATUMOFFERTE) as rank


FROM ${ref("sam_trajects_def_offerte")} SALESTRAJECT

LEFT JOIN 
(SELECT * FROM ${ref("sam_offerte_merk_model_occasion")}) OFFERTE 
ON SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = OFFERTE.OFFERTE_DTCMEDIA_CRM_ID 
AND SALESTRAJECT.TRAJECT_DEFINITIEFOFFERTEID = OFFERTE.OFFERTE_OFFERTEID
)
-- WHERE OFFERTESTATUS_OMSCHRIJVING = "Overeenkomst"

GROUP BY
TRAJECT_DTCMEDIA_CRM_ID,
TRAJECT_TRAJECTID
`
let refs = pk.getRefs()
module.exports = {query, refs}
