
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `

SELECT 
OFFERTE_DTCMEDIA_CRM_ID,
OFFERTE_OFFERTEID as OFFERTE_OFFERTEID,
OFFERTE_TRAJECTID,
IFNULL(RELATIE_EMAIL, RELATIE_EMAILZAKELIJK) AS RELATIE_EMAIL,
OFFERTESTATUS_OFFERTESTATUSID,
OFFERTESTATUS_OMSCHRIJVING,
--aantal_offertes,
OFFERTE_DATUMOFFERTE,
OFFERTE_TOTAALBEDRAG,
AUTOPRIJSCONSUMENT,
NETTOCATPRIJS,
OFFERTEVTR_TRANSACTIERESULTAAT,
OFFERTEVTR_BRUTOMARGEBEDRAG,
IFNULL(AFLEVERINGMODEL_OMSCHRIJVING, OCCASION.OCCASION_MODELNAAM) as AFLEVERINGMODEL_OMSCHRIJVING,
IFNULL(AUTOMERK_OMSCHRIJVING, OCCASION.OCCASION_MERKNAAM) MERK_OMSCHRIJVING,
OCCASION.OCCASION_KENTEKEN,
OCCASION.OCCASION_KILOMETERSTAND,
OCCASION.OCCASION_DATUMDEEL1,
OCCASION.OCCASION_UITVOERINGNAAM,
OCCASION.OCCASION_BOUWJAAR,
INRUIL_OCCASION.OCCASION_KENTEKEN AS INRUILOCCASION_KENTEKEN,
INRUIL_OCCASION.OCCASION_MERKNAAM AS INRUILOCCASION_MERKNAAM,
INRUIL_OCCASION.OCCASION_MODELNAAM AS INRUILOCCASION_MODELNAAM,
INRUIL_OCCASION.OCCASION_DATUMDEEL1 AS INRUILOCCASION_DATUMDEEL1,
INRUIL_OCCASION.OCCASION_UITVOERINGNAAM AS INRUILOCCASION_UITVOERINGNAAM,
INRUIL_OCCASION.OCCASION_BOUWJAAR AS INRUILOCCASION_BOUWJAAR,

ROW_NUMBER() OVER (PARTITION BY OFFERTE_DTCMEDIA_CRM_ID, OFFERTE_TRAJECTID ORDER BY OFFERTE_DATUMOFFERTE DESC) AS offerte_rank

FROM ${ref("sam_offertes")} OFFERTE

LEFT JOIN ${ref("sam_offerte_status")} OFFERTESTATUS
ON OFFERTE_OFFERTESTATUSID = OFFERTESTATUS_OFFERTESTATUSID AND OFFERTE_DTCMEDIA_CRM_ID = OFFERTESTATUS_DTCMEDIA_CRM_ID	

LEFT JOIN ${ref("sam_relatie")} RELATIE
ON OFFERTE_RELATIEID = RELATIE_RELATIEID AND OFFERTE_DTCMEDIA_CRM_ID = RELATIE_DTCMEDIA_CRM_ID

LEFT JOIN 
${ref("sam_offerte_vtr")} OFFERTEVTR ON OFFERTE.OFFERTE_DTCMEDIA_CRM_ID = OFFERTEVTR.OFFERTEVTR_DTCMEDIA_CRM_ID AND OFFERTE.OFFERTE_OFFERTEID = OFFERTEVTR.OFFERTEVTR_OFFERTEID

LEFT JOIN 
${ref("sam_aflevering_model")} AFLEVERINGMODEL ON OFFERTE.OFFERTE_DTCMEDIA_CRM_ID = AFLEVERINGMODEL.AFLEVERINGMODEL_DTCMEDIA_CRM_ID AND OFFERTE.OFFERTE_AFLEVERINGMODELID = AFLEVERINGMODEL.AFLEVERINGMODEL_AFLEVERINGMODELID

LEFT JOIN 
${ref("sam_occasion")} OCCASION ON OFFERTE.OFFERTE_DTCMEDIA_CRM_ID = OCCASION.OCCASION_DTCMEDIA_CRM_ID AND OFFERTE.OFFERTE_OCCASIONID = OCCASION.OCCASION_OCCASIONID

LEFT JOIN 
${ref("sam_occasion")} INRUIL_OCCASION ON OFFERTE.OFFERTE_DTCMEDIA_CRM_ID = INRUIL_OCCASION.OCCASION_DTCMEDIA_CRM_ID AND OFFERTE.OFFERTE_INRUILOCCASIONID = INRUIL_OCCASION.OCCASION_OCCASIONID

LEFT JOIN 
${ref("sam_automerk")} MERK ON OFFERTE.OFFERTE_DTCMEDIA_CRM_ID = MERK.AUTOMERK_DTCMEDIA_CRM_ID AND OFFERTE.OFFERTE_AUTOMERKID = MERK.AUTOMERK_AUTOMERKID

`
let refs = pk.getRefs()
module.exports = {query, refs}
