
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `


SELECT 
SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID as offerte_SALESTRAJECT_DTCMEDIA_CRM_ID,
SALESTRAJECT.TRAJECT_TRAJECTID as offerte_SALESTRAJECT_TRAJECTID,
SALESTRAJECT.TRAJECT_AFGERONDDATUM as offerte_SALESTRAJECT_AFGERONDDATUM,
SALESTRAJECT.TRAJECT_CREATIEDATUM as offerte_SALESTRAJECT_CREATIEDATUM,
SALESTRAJECT.TRAJECT_SOORTAUTO as offerte_SALESTRAJECT_SOORTAUTO,
SALESTRAJECT.TRAJECTSTATUSID as offerte_SALESTRAJECT_TRAJECTSTATUSID,
SALESTRAJECT.TRAJECT_TRAJECTAFSLUITREDENID AS offerte_SALESTRAJECT_TRAJECTAFSLUITREDENID,
IFNULL(OFFERTE.unieke_getekende_offerte, LAST_OFFERTE.OFFERTE_OFFERTEID) as offerte_OFFERTE_OFFERTEID,
SALESTRAJECT.TRAJECT_DEFINITIEFOFFERTEID AS TRAJECT_DEFINITIEFOFFERTEID,
unieke_getekende_offerte,
unieke_getekende_overeenkomst,
getekende_offertes,
IFNULL(OFFERTE.OFFERTE_DATUMOFFERTE, LAST_OFFERTE.OFFERTE_DATUMOFFERTE) as offerte_OFFERTE_DATUMOFFERTE,
IFNULL(OFFERTE.OFFERTESTATUS_OMSCHRIJVING, LAST_OFFERTE.OFFERTESTATUS_OMSCHRIJVING) as offerte_OFFERTESTATUS_OMSCHRIJVING,
IFNULL(OFFERTE.OFFERTE_TOTAALBEDRAG, LAST_OFFERTE.OFFERTE_TOTAALBEDRAG) as offerte_OFFERTE_TOTAALBEDRAG,
IFNULL(OFFERTE.AUTOPRIJSCONSUMENT, LAST_OFFERTE.AUTOPRIJSCONSUMENT) as offerte_AUTOPRIJSCONSUMENT,
IFNULL(OFFERTE.OCCASION_KENTEKEN, LAST_OFFERTE.OCCASION_KENTEKEN) as offerte_OCCASION_KENTEKEN,
IFNULL(OFFERTE.OCCASION_KILOMETERSTAND, LAST_OFFERTE.OCCASION_KILOMETERSTAND) as offerte_OCCASION_KILOMETERSTAND,
IFNULL(OFFERTE.OCCASION_DATUMDEEL1, LAST_OFFERTE.OCCASION_DATUMDEEL1) as offerte_OCCASION_DATUMDEEL1,
IFNULL(OFFERTE.OFFERTEVTR_TRANSACTIERESULTAAT, LAST_OFFERTE.OFFERTEVTR_TRANSACTIERESULTAAT) as offerte_OFFERTEVTR_TRANSACTIERESULTAAT,
IFNULL(OFFERTE.OFFERTEVTR_BRUTOMARGEBEDRAG, LAST_OFFERTE.OFFERTEVTR_BRUTOMARGEBEDRAG) as offerte_OFFERTEVTR_BRUTOMARGEBEDRAG,
DEALER_NAAM as offerte_DEALER_NAAM,
VERKOPER_NAAM as offerte_VERKOPER_NAAM,
VERKOPER_VOORVOEGSEL as offerte_VERKOPER_VOORVOEGSEL,
RELATIE_RELATIEID as offerte_RELATIE_RELATIEID,
RELATIE_ACHTERNAAM as offerte_RELATIE_ACHTERNAAM,
RELATIE_TUSSENVOEGSELS as RELATIE_TUSSENVOEGSELS,
--RELATIEEXTERN_EXTERNID AS RELATIE_EXTERNID,
--RELATIEEXTERN_SOORTEXTERNID AS RELATIE_SOORTEXTERNID,
--RELATIE_VOORLETTERS as RELATIE_VOORLETTERS,
--RELATIE_VOORNAAM as RELATIE_VOORNAAM,
RELATIE_GEBOORTEDATUM as RELATIE_GEBOORTEDATUM,
RELATIE_GESLACHT as RELATIE_GESLACHT,
RELATIE.RELATIE_EMAIL as offerte_RELATIE_EMAIL,
RELATIE.RELATIE_EMAILOPTIN,
RELATIE.RELATIE_TEL1,
RELATIE.RELATIE_TEL1OPTIN,
RELATIE.RELATIE_TEL2,
RELATIE.RELATIE_TEL2OPTIN,
RELATIE.RELATIE_EMAILZAKELIJK,
RELATIE.RELATIE_EMAILZAKELIJKOPTIN,
RELATIE_SOORTRELATIEID as offerte_RELATIE_SOORTRELATIEID,
ADRES_HUISNUMMER as offerte_ADRES_HUISNUMMER,
ADRES_HUISNRTOEVOEGING offerte_ADRES_HUISNRTOEVOEGING,
ADRES_POSTCODE as offerte_ADRES_POSTCODE,
IFNULL(OFFERTE.AFLEVERINGMODEL_OMSCHRIJVING, LAST_OFFERTE.AFLEVERINGMODEL_OMSCHRIJVING) as offerte_AFLEVERINGMODEL_OMSCHRIJVING,
IFNULL(OFFERTE.MERK_OMSCHRIJVING, LAST_OFFERTE.MERK_OMSCHRIJVING) as offerte_MERK_OMSCHRIJVING,
UPPER(TRIM(REPLACE(IFNULL(OFFERTE.INRUILOCCASION_KENTEKEN, LAST_OFFERTE.INRUILOCCASION_KENTEKEN), "-", ""))) as INRUILOCCASION_KENTEKEN,
IFNULL(OFFERTE.INRUILOCCASION_MERKNAAM, LAST_OFFERTE.INRUILOCCASION_MERKNAAM) as INRUILOCCASION_MERKNAAM,
IFNULL(OFFERTE.INRUILOCCASION_MODELNAAM, LAST_OFFERTE.INRUILOCCASION_MODELNAAM) as INRUILOCCASION_MODELNAAM,
LEADTRAJECT.TRAJECT_TRAJECTID as offerte_LEADTRAJECT_TRAJECTID,
LEADTRAJECT.TRAJECT_AFGERONDDATUM as offerte_LEADTRAJECT_AFGERONDDATUM,
TRAJECTEXTERN_EXTERNGUID as offerte_LEADTRAJECT_EXTERNLEADID,
LEADTRAJECT.TRAJECT_EERSTEKWALIFICATIE as offerte_LEADTRAJECT_EERSTEKWALIFICATIE,
TRAJECTEXTERN_SOORTLEADSBRONID as offerte_LEADTRAJECT_SOORTLEADSBRONID,
HERKOMST_OMSCHRIJVING as offerte_HERKOMST_OMSCHRIJVING,
TRAJECTAFSLUITREDEN_OMSCHRIJVING as offerte_TRAJECTAFSLUITREDEN_OMSCHRIJVING

FROM 
(SELECT * FROM ${ref("sam_trajects_offertes")} WHERE TRAJECT_CREATIEDATUM >= DATETIME_SUB(CURRENT_DATETIME(), INTERVAL 25 MONTH)) SALESTRAJECT

LEFT JOIN 
${ref("sam_dealer")} DEALER ON SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = DEALER.DEALER_DTCMEDIA_CRM_ID AND SALESTRAJECT.TRAJECT_DEALERID = DEALER.DEALER_DEALERID

LEFT JOIN 
${ref("sam_verkoper")} VERKOPER ON SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = VERKOPER.VERKOPER_DTCMEDIA_CRM_ID AND SALESTRAJECT.TRAJECT_VERKOPERID = VERKOPER.VERKOPER_GEBRUIKERID

LEFT JOIN 
${ref("sam_offerte_merk_model_occasion_def_offerte")} OFFERTE ON SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = OFFERTE.TRAJECT_DTCMEDIA_CRM_ID AND SALESTRAJECT.TRAJECT_TRAJECTID = OFFERTE.TRAJECT_TRAJECTID

LEFT JOIN 
(SELECT * FROM ${ref("sam_offerte_merk_model_occasion")}  WHERE offerte_rank = 1) LAST_OFFERTE ON SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = LAST_OFFERTE.OFFERTE_DTCMEDIA_CRM_ID AND SALESTRAJECT.TRAJECT_TRAJECTID = LAST_OFFERTE.OFFERTE_TRAJECTID

LEFT JOIN 
${ref("sam_relatie")} RELATIE ON SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = RELATIE.RELATIE_DTCMEDIA_CRM_ID AND SALESTRAJECT.TRAJECT_RELATIEID = RELATIE.RELATIE_RELATIEID

LEFT JOIN 
${ref("sam_adres")} ADRES ON RELATIE.RELATIE_DTCMEDIA_CRM_ID = ADRES.ADRES_DTCMEDIA_CRM_ID AND RELATIE.RELATIE_RELATIEID = ADRES.ADRES_RELATIEID

LEFT JOIN 
${ref("sam_trajects_leads")} LEADTRAJECT ON SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = LEADTRAJECT.TRAJECT_DTCMEDIA_CRM_ID AND SALESTRAJECT.TRAJECT_PREVTRAJECTID = LEADTRAJECT.TRAJECT_TRAJECTID

LEFT JOIN ${ref("sam_trajects_extern")} TRAJECTEXTERN
ON LEADTRAJECT.TRAJECT_TRAJECTID = TRAJECTEXTERN_TRAJECTID AND LEADTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = TRAJECTEXTERN_DTCMEDIA_CRM_ID

LEFT JOIN 
${ref("sam_herkomst")} HERKOMST ON SALESTRAJECT.TRAJECT_HERKOMSTID = HERKOMST.HERKOMST_HERKOMSTID AND SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = HERKOMST.HERKOMST_DTCMEDIA_CRM_ID

LEFT JOIN 
${ref("sam_afsluitreden")} AFSLUITREDEN ON SALESTRAJECT.TRAJECT_TRAJECTAFSLUITREDENID = AFSLUITREDEN.TRAJECTAFSLUITREDENID AND SALESTRAJECT.TRAJECT_DTCMEDIA_CRM_ID = AFSLUITREDEN.TRAJECTAFSLUITREDEN_DTCMEDIA_CRM_ID

`
let refs = pk.getRefs()
module.exports = {query, refs}
