/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `

SELECT
  offerte_SALESTRAJECT_DTCMEDIA_CRM_ID,
  offerte_SALESTRAJECT_TRAJECTID,
  DATE(offerte_SALESTRAJECT_AFGERONDDATUM) AS offerte_SALESTRAJECT_AFGERONDDATUM,
  DATE(offerte_SALESTRAJECT_CREATIEDATUM) AS offerte_SALESTRAJECT_CREATIEDATUM,
  offerte_SALESTRAJECT_SOORTAUTO,
  offerte_OFFERTESTATUS_OMSCHRIJVING,
  offerte_OFFERTE_TOTAALBEDRAG,
  offerte_AUTOPRIJSCONSUMENT,
  offerte_HERKOMST_OMSCHRIJVING,
  offerte_OFFERTE_OFFERTEID,
  offerte_OFFERTE_DATUMOFFERTE,
  offerte_OFFERTESTATUS_OMSCHRIJVING,
  getekende_offertes,
  offerte_SALESTRAJECT_TRAJECTSTATUSID,
  offerte_OFFERTEVTR_BRUTOMARGEBEDRAG,
  offerte_MERK_OMSCHRIJVING,
  offerte_AFLEVERINGMODEL_OMSCHRIJVING,
  offerte_DEALER_NAAM,
  offerte_VERKOPER_VOORVOEGSEL,
  offerte_VERKOPER_NAAM,
  offerte_LEADTRAJECT_TRAJECTID,
  offerte_LEADTRAJECT_EERSTEKWALIFICATIE,
  order_TRAJECT_TRAJECTID,
  order_AFLEVERTRAJECT_AANTAL,
  afleveringstatus_omschrijving,
  SOORTKLANTCATEGORIE_OMSCHRIJVING,
  SOORTBRANDSTOF_OMSCHRIJVING,
  ORDERDATUM

FROM ${ref("stg_sam_offertes")} offertes

LEFT JOIN ${ref("stg_sam_orders")} orders
ON offerte_SALESTRAJECT_TRAJECTID = order_TRAJECT_TRAJECTID
AND offerte_SALESTRAJECT_DTCMEDIA_CRM_ID = orders.DTCMEDIA_CRM_ID

WHERE order_TRAJECT_TRAJECTID <> ""
`
let refs = pk.getRefs()
module.exports = {query, refs}
