
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `

SELECT
DTCMEDIA_CRM_ID,
sales_traject.TRAJECT_TRAJECTID as order_TRAJECT_TRAJECTID,
COUNT(DISTINCT(aflever_traject.TRAJECT_TRAJECTID)) AS order_AFLEVERTRAJECT_AANTAL,
MAX(AFLEVERINGSTATUSID) AS order_AFLEVERING_AFLEVERINGSTATUSID,
MAX(AFLEVERINGSTATUS_OMSCHRIJVING) AS afleveringstatus_omschrijving,
MAX(aflevering.SOORTKLANTCATEGORIEID) AS soortklantcategorieid,
MAX(soort_klantcategorie.SOORTKLANTCATEGORIE_OMSCHRIJVING) AS SOORTKLANTCATEGORIE_OMSCHRIJVING,
MAX(AFLEVERDEALERID) AS AFLEVERDEALERID,
MAX(DEALER_NAAM) AS DEALER_NAAM,
MAX(SOORTBRANDSTOF_OMSCHRIJVING) AS SOORTBRANDSTOF_OMSCHRIJVING,
--SUM(CAST(VTRBEDRAG AS FLOAT64)) AS order_AFLEVERING_VTRBEDRAG,
--AVG(CAST(VTRBEDRAG AS FLOAT64)) AS order_AFLEVERING_VTRBEDRAG_avg,
MAX(ORDERDATUM) AS ORDERDATUM,
MAX(AUTOVERKOCHTDATUM) AS AUTOVERKOCHTDATUM,
MAX(AUTOBINNENDATUM) AS AUTOBINNENDATUM,
MAX(AFSPRAAKAFLEVERDATUMSTART) AS AFSPRAAKAFLEVERDATUMSTART,
MAX(AFSPRAAKAFLEVERDATUMEIND) AS AFSPRAAKAFLEVERDATUMEIND,
MAX(AUTOAFGELEVERDDATUM) AS AUTOAFGELEVERDDATUM,
MAX(AKDKLANT) AS AKDKLANT,
MAX(AKDORIGINEEL) AS AKDORIGINEEL,
MAX(AKDHUIDIG) AS AKDHUIDIG,
MAX(REGISTRATIEDATUM) AS REGISTRATIEDATUM,
MAX(AUTOBESTELDDATUM) AS AUTOBESTELDDATUM,
MAX(REGSELECTIEDATUM) AS REGSELECTIEDATUM

FROM(
    SELECT 
    DTCMEDIA_CRM_ID,
    AFLEVERINGID,
    TRAJECTID,
    AFLEVERINGSTATUSID,
    CASE
        WHEN AFLEVERINGSTATUSID = '1' THEN 'Order'
        WHEN AFLEVERINGSTATUSID = '2' THEN 'Goedgekeurd'
        WHEN AFLEVERINGSTATUSID = '3' THEN 'Besteld'
        WHEN AFLEVERINGSTATUSID = '4' THEN 'Afgeleverd'
        WHEN AFLEVERINGSTATUSID = '5' THEN 'Afgekeurd'
        WHEN AFLEVERINGSTATUSID = '6' THEN 'Niet te bestellen'
        ELSE NULL 
    END AS AFLEVERINGSTATUS_OMSCHRIJVING,
    GOEDGEKEURDDOOR,
    GOEDGEKEURDDATUM,
    ORDERDATUM,
    AUTOBINNENDATUM,
    AFSPRAAKAFLEVERDATUMSTART,
    AFSPRAAKAFLEVERDATUMEIND,
    AUTOAFGELEVERDDATUM,
    AKDKLANT, -- aankondiging levering klant
    AKDORIGINEEL,
    AKDHUIDIG,
    DEALERNUMMER,
    ORDERNUMMER,
    CHASSISNUMMER,
    KENTEKEN,
    SOORTKENTEKENID,
    SOORTBRANDSTOFID,
    CASE
        WHEN SOORTBRANDSTOFID = '-1' THEN 'Onbekend'
        WHEN SOORTBRANDSTOFID = '0' THEN 'Alle brandstoffen'
        WHEN SOORTBRANDSTOFID = '1' THEN 'Benzine'
        WHEN SOORTBRANDSTOFID = '2' THEN 'LPG'
        WHEN SOORTBRANDSTOFID = '3' THEN 'Diesel'
        WHEN SOORTBRANDSTOFID = '4' THEN 'Elektrisch'
        WHEN SOORTBRANDSTOFID = '5' THEN 'PHEV'
        WHEN SOORTBRANDSTOFID = '6' THEN 'HEV'
        ELSE NULL
    END AS SOORTBRANDSTOF_OMSCHRIJVING,
    DATUMDEEL1,
    ISVOORRAAD,
    AUTOVERKOCHTDATUM,
    AUTOMERKID,
    AFLEVERINGMODELID,
    AUTOOMSCHRIJVING,
    DEALERID,
    AFLEVERDEALERID,
    REGISTRATIEDATUM,
    OFFERTENUMMER,
    FACTUURNRKLANT,
    KENTEKENAANGEVRAAGD,
    OCCASIONID,
    NETTOCATPRIJS,
    VTRBEDRAG,
    AUTOBESTELDDATUM,
    SOORTKLANTCATEGORIEID,
    REGSELECTIEDATUM,
    KENTEKENBINNEN,
    LEASEORDERNUMMER,
    FACTUURDATUMKLANT,
    OFFERTEID,
    AUTOTYPE,
    EXTERNID

FROM ${ref("sam_aflevering")}
WHERE AFLEVERINGSTATUSID != '5') aflevering

LEFT JOIN ${ref("sam_aflever_trajecten")} aflever_traject
ON aflevering.TRAJECTID = aflever_traject.TRAJECT_TRAJECTID

LEFT JOIN ${ref("sam_sales_trajecten")} sales_traject
ON aflever_traject.TRAJECT_PREVTRAJECTID = sales_traject.TRAJECT_TRAJECTID

LEFT JOIN ${ref("sam_soortklantcategorie")} soort_klantcategorie
ON aflevering.SOORTKLANTCATEGORIEID = soort_klantcategorie.SOORTKLANTCATEGORIEID

LEFT JOIN 
${ref("sam_dealer")} dealer 
ON aflevering.AFLEVERDEALERID = dealer.DEALER_DEALERID

WHERE sales_traject.TRAJECT_TRAJECTID <> ""

GROUP BY
DTCMEDIA_CRM_ID,
order_TRAJECT_TRAJECTID

`
let refs = pk.getRefs()
module.exports = {query, refs}
