/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `

SELECT
    event_date,
    CONCAT(IFNULL(user_pseudo_id, ""), "_", CAST(event_timestamp AS STRING), "_", event_name) AS unique_event_id,
    event_timestamp,
    event_name,
    user_pseudo_id,
    event_bundle_sequence_id,
    (SELECT value.int_value FROM unnest(event_params) WHERE key = 'ga_session_id') as event_ga_session_id,
    (SELECT value.int_value FROM unnest(event_params) WHERE key = 'ga_session_number') as event_ga_session_number,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'gclid') as event_gclid,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'page_referrer') as event_page_referrer,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'page_location') as event_page_location,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'page_title') as event_page_title,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'term') as event_term,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'source') as event_source,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'medium') as event_medium,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'campaign_id') as event_campaign_id,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'campaign') as event_campaign,
    (SELECT value.int_value from unnest(event_params) where key = 'engagement_time_msec') AS event_engagement_time_msec,
    (SELECT value.int_value from unnest(event_params) where key = 'entrances') as event_entrances,
    (SELECT value.string_value from unnest(event_params) where key = 'session_engaged') as event_session_engaged,
    (SELECT value.int_value from unnest(event_params) where key = 'engaged_session_event') as event_engaged_session_event,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'buy_status') as event_buy_status,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'buy_model') as event_buy_model,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'buy_plaats') as event_buy_plaats,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'buy_brand') as event_buy_brand,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'trade_in_model') as event_trade_in_model,
    (SELECT value.string_value FROM unnest(event_params) WHERE key = 'trade_in_brand') as event_trade_in_brand,
    privacy_info.analytics_storage as privacy_analytics_storage,
    privacy_info.ads_storage as privacy_ads_storage,
    privacy_info.uses_transient_token as privacy_uses_transient_token,
    user_first_touch_timestamp,
    user_ltv.revenue as user_ltv_revenue,
    user_ltv.currency as user_ltv_currency,
    device.category as device_category,
    device.mobile_brand_name as device_mobile_brand_name,
    device.mobile_model_name as device_mobile_model_name,
    device.mobile_marketing_name as device_mobile_marketing_name,
    device.operating_system as device_operating_system,
    device.operating_system_version as device_operating_system_version,
    device.language as device_language,
    device.is_limited_ad_tracking as device_is_limited_ad_tracking,
    device.web_info.browser as device_webinfo_browser,
    device.web_info.browser_version as device_webinfo_browser_version,
    device.web_info.hostname as device_webinfo_hostname,
    geo.city as geo_city,
    geo.country as geo_country,
    geo.continent as geo_continent,
    geo.region as geo_region,
    geo.sub_continent as geo_sub_continent,
    traffic_source.name as traffic_source_name,
    traffic_source.medium as traffic_source_medium,
    traffic_source.source as traffic_source_source,
    stream_id,
    platform,
    ecommerce.total_item_quantity as ecommerce_total_item_quantity,
    ecommerce.purchase_revenue as ecommerce_purchase_revenue,
    ecommerce.unique_items as ecommerce_unique_items,
    ecommerce.transaction_id as ecommerce_transaction_id,
    --items.item_id,
    --items.item_name,
    collected_traffic_source.manual_campaign_id as collected_traffic_source_manual_campaign_id,
    collected_traffic_source.manual_campaign_name as collected_traffic_source_manual_campaign_name,
    collected_traffic_source.manual_source as collected_traffic_source_manual_source,
    collected_traffic_source.manual_medium as collected_traffic_source_manual_medium,
    collected_traffic_source.manual_term as collected_traffic_source_manual_term,
    collected_traffic_source.manual_content as collected_traffic_source_manual_content,
    collected_traffic_source.gclid as collected_traffic_source_gclid,
    is_active_user,
    batch_event_index,
    batch_page_id,
    batch_ordering_id,
    session_traffic_source_last_click.manual_campaign.campaign_id as manual_campaign_last_click_campaign_id,
    session_traffic_source_last_click.manual_campaign.campaign_name as manual_campaign_last_click_campaign_name,
    session_traffic_source_last_click.manual_campaign.source as manual_campaign_last_click_source,
    session_traffic_source_last_click.manual_campaign.medium as manual_campaign_last_click_medium,
    session_traffic_source_last_click.manual_campaign.term as manual_campaign_last_click_term,
    session_traffic_source_last_click.manual_campaign.content as manual_campaign_last_click_content,
    session_traffic_source_last_click.google_ads_campaign.customer_id as google_ads_campaign_last_click_customer_id,
    session_traffic_source_last_click.google_ads_campaign.account_name as google_ads_campaign_last_click_account_name,
    session_traffic_source_last_click.google_ads_campaign.campaign_id as google_ads_campaign_last_click_campaign_id,
    session_traffic_source_last_click.google_ads_campaign.campaign_name as google_ads_campaign_last_click_campaign_name,
    session_traffic_source_last_click.google_ads_campaign.ad_group_id as google_ads_campaign_last_click_ad_group_id,
    session_traffic_source_last_click.google_ads_campaign.ad_group_name as google_ads_campaign_last_click_ad_group_name,
    session_traffic_source_last_click.cross_channel_campaign.campaign_id as cross_channel_campaign_last_click_campaign_id,
    session_traffic_source_last_click.cross_channel_campaign.campaign_name as cross_channel_campaign_last_click_campaign_name,
    session_traffic_source_last_click.cross_channel_campaign.source as cross_channel_campaign_last_click_source,
    session_traffic_source_last_click.cross_channel_campaign.medium as cross_channel_campaign_last_click_medium,
    session_traffic_source_last_click.cross_channel_campaign.source_platform as cross_channel_campaign_last_click_source_platform,
    session_traffic_source_last_click.cross_channel_campaign.default_channel_group as cross_channel_campaign_last_click_default_channel_group,
    session_traffic_source_last_click.cross_channel_campaign.primary_channel_group as cross_channel_campaign_last_click_primary_channel_group,
    session_traffic_source_last_click.sa360_campaign.campaign_id as sa360_campaign_last_click_campaign_id, -- let op (not set)
    session_traffic_source_last_click.sa360_campaign.campaign_name as sa360_campaign_last_click_campaign_name,
    session_traffic_source_last_click.sa360_campaign.source as sa360_campaign_last_click_source,
    session_traffic_source_last_click.sa360_campaign.medium as sa360_campaign_last_click_medium,
    session_traffic_source_last_click.cm360_campaign.campaign_id as cm360_campaign_last_click_campaign_id,
    session_traffic_source_last_click.cm360_campaign.campaign_name as cm360_campaign_last_click_campaign_name,
    session_traffic_source_last_click.cm360_campaign.source as cm360_campaign_last_click_source,
    session_traffic_source_last_click.cm360_campaign.medium as cm360_campaign_last_click_medium,
    session_traffic_source_last_click.dv360_campaign.campaign_id as dv360_campaign_last_click_campaign_id,
    session_traffic_source_last_click.dv360_campaign.campaign_name as dv360_campaign_last_click_campaign_name,
    session_traffic_source_last_click.dv360_campaign.source as dv360_campaign_last_click_source,
    session_traffic_source_last_click.dv360_campaign.medium as dv360_campaign_last_click_medium,
    session_traffic_source_last_click.dv360_campaign.insertion_order_name as dv360_campaign_last_click_insertion_order_name,
    session_traffic_source_last_click.dv360_campaign.line_item_name as dv360_campaign_last_click_line_item_name,
    session_traffic_source_last_click.dv360_campaign.partner_name as dv360_campaign_last_click_partner_name,
    publisher.ad_revenue_in_usd as publisher_ad_revenue_in_usd,
    publisher.ad_format as publisher_ad_format,
    publisher.ad_source_name as publisher_ad_source_name,
    publisher.ad_unit_id as publisher_ad_unit_id

FROM ${ref("events_*")}

`
let refs = pk.getRefs()
for (let r in refs) {
    query += refs[r].database + "." + refs[r].schema + "." + refs[r].name
}
module.exports = {query, refs}