/*config*/
const {join, ref, getRefs, ifSource, ifNull} = require("../../sources");
let query = `

SELECT
    JSON_VALUE(PAYLOAD, '$.pk_crm_id') AS pk_crm_id,
    JSON_VALUE(PAYLOAD, '$.type') AS type,
    JSON_VALUE(PAYLOAD, '$.LEFleadID') AS LEFleadID,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M', JSON_VALUE(PAYLOAD, '$.response.overige.aangemaaktDatum')) AS aangemaaktDatum,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M', JSON_VALUE(PAYLOAD, '$.response.overige.eersteDeadline')) AS eersteDeadline,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M', JSON_VALUE(PAYLOAD, '$.response.overige.ingezienDatum')) AS ingezienDatum,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M', JSON_VALUE(PAYLOAD, '$.response.overige.eersteContactpoging')) AS eersteContactpoging,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M', JSON_VALUE(PAYLOAD, '$.response.overige.afgerondDatum')) AS afgerondDatum,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalIngezien') AS aantalIngezien,
    JSON_VALUE(PAYLOAD, '$.response.overige.doorlooptijdTotIngezien') AS doorlooptijdTotIngezien,
    JSON_VALUE(PAYLOAD, '$.response.overige.doorlooptijdTotEersteContactpoging') AS doorlooptijdTotEersteContactpoging,
    JSON_VALUE(PAYLOAD, '$.response.overige.doorlooptijdEersteContactpogingBinnenOpvolgtijdenMinuten') AS doorlooptijdEersteContactpogingBinnenOpvolgtijdenMinuten,
    JSON_VALUE(PAYLOAD, '$.response.overige.deadlineGehaald') AS deadlineGehaald,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalActiesOpLead') AS aantalActiesOpLead,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalNietBereikt') AS aantalNietBereikt,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalOpnieuwIngepland') AS aantalOpnieuwIngepland,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalDoorgezet') AS aantalDoorgezet,
    JSON_VALUE(PAYLOAD, '$.response.leadID') AS leadID,
    JSON_VALUE(PAYLOAD, '$.response.bron') AS bron,
    JSON_VALUE(PAYLOAD, '$.response.systeem') AS systeem,
    JSON_VALUE(PAYLOAD, '$.response.eersteKwalificatie') AS kwalificatie,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadType') AS leadType,
    JSON_VALUE(PAYLOAD, '$.response.overige.initiatief') AS initiatief,
    JSON_VALUE(PAYLOAD, '$.response.overige.soortLead') AS soortLead,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadOmschrijving') AS leadOmschrijving,
    IFNULL(rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.overige.leadResultaten'), 'Vestiging'), JSON_VALUE(PAYLOAD, '$.response.vestiging')) AS vestiging,
    IFNULL(rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.overige.leadResultaten'),'Verkoper'), JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.medewerker')) AS medewerker,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M', JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.startGesprek')) AS laatsteStatus_startGesprek,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.resultaat') AS resultaat,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.overige.leadResultaten'),'Omschrijving') AS afsluitreden,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.overige.leadResultaten'),'Opmerking') AS afsluitreden_opmerking,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.overige.leadResultaten'),'DatumVan') AS leadresultaat_datumVan,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.overige.leadResultaten'),'DatumTot') AS leadresultaat_datumTot,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.overige.leadResultaten'),'Verkoper') AS leadresultaat_verkoper,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.overige.leadResultaten'),'Vestiging') AS leadresultaat_vestiging,
    JSON_VALUE(PAYLOAD, '$.response.overige.heeftOfferte') AS heeftOfferte,
    JSON_VALUE(PAYLOAD, '$.response.overige.heeftOrder') AS heeftOrder,
    JSON_VALUE(PAYLOAD, '$.response.overige.ordernummer') AS ordernummer,
    JSON_VALUE(PAYLOAD, '$.response.overige.dealernummer') AS dealernummer,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteMutatieDatum') AS laatsteMutatieDatum,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.achternaam') AS achternaam,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.tussenvoegsel') AS tussenvoegsel,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.voorletters') AS voorletters,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.geslachtType') AS geslachtType,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.relatieType') AS relatieType,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.klantInfo.adressen'),'postcode') AS postcode,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.klantInfo.adressen'),'huisnummer') AS huisnummer,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.klantInfo.adressen'),'huisnummertoevoeging') AS huisnummertoevoeging,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.klantInfo.adressen'),'straat') AS straat,
    rawdata.getAdres(JSON_EXTRACT(PAYLOAD, '$.response.klantInfo.adressen'),'plaats') AS plaats,
    rawdata.getEmail(IFNULL(JSON_EXTRACT(PAYLOAD, '$.response.klantInfo.contactwijzen'), "[]")) AS contactwijzen,
    rawdata.getTelefoon(IFNULL(JSON_EXTRACT(PAYLOAD, '$.response.klantInfo.contactwijzen'), "[]")) AS contactwijzen_Telefoon,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.bewaartermijn') AS klantinfo_bewaartermijn,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Merk') AS Merk,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Model') AS MODEL,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.AutoSoort') AS AutoSoort,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.BrandstofType') AS Brandstof,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Bouwjaar') AS Bouwjaar,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Uitvoering') AS Uitvoering,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Kenteken') AS Kenteken,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Merk') AS huidigMerk,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Model') AS huidigModel,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Uitvoering') AS huidigUitvoering,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.BrandstofType') AS huidigBrandstof,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Kenteken') AS huidigKenteken,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Bouwjaar') AS huidigBouwjaar,
    REGEXP_EXTRACT(
        IF (JSON_VALUE(PAYLOAD, '$.response.google_clientid') <> '', JSON_VALUE(PAYLOAD, '$.response.google_clientid'),
        IF (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.OverigeVelden.google_clientid') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.OverigeVelden.google_clientid'),
        IF (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Voertuig Informatie.ClientID') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Voertuig Informatie.ClientID'),
        IF (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Informatie.ClientID') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Informatie.ClientID'),
        IF (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Extra.ClientID') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Extra.ClientID'),
        IF (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Overige formulier velden.google_clientid') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Overige formulier velden.google_clientid'), NULL) ) ) ) ) ), '\\\d{1,}.\\\d{1,}$'
    ) AS google_clientid,
    RECEIVEDON,
    ACTION

FROM
    ${ref("df_rawdata_views", "lefBiDataProducer_lasttransaction")}

`
let refs = getRefs()
module.exports = {query, refs}