/*config*/
const {join, ref, getRefs, ifSource, ifNull} = require("../../sources");
let query = `

SELECT * EXCEPT(
email_1, telefoon_1, email_2, telefoon_2, email_3, telefoon_3,
klantInfo_contactwijzen_contactwijzeType, klantInfo_contactwijzen_value, klantInfo_contactwijzen_heeftVoorkeur,
klantInfo_contactwijzen_contactwijzeType_1, klantInfo_contactwijzen_value_1, klantInfo_contactwijzen_heeftVoorkeur_1,
klantInfo_contactwijzen_contactwijzeType_2, klantInfo_contactwijzen_value_2, klantInfo_contactwijzen_heeftVoorkeur_2
),
IFNULL(IFNULL(email_1, email_2), email_3) as email,
IFNULL(IFNULL(telefoon_1, telefoon_2), telefoon_3) as telefoon

FROM(
SELECT
    JSON_VALUE(PAYLOAD, '$.pk_crm_id') AS pk_crm_id,
    JSON_VALUE(PAYLOAD, '$.type') AS type,
    JSON_VALUE(PAYLOAD, '$.LEFleadID') AS LEFleadID,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadType') AS leadType,
    JSON_VALUE(PAYLOAD, '$.response.overige.initiatief') AS initiatief,
    JSON_VALUE(PAYLOAD, '$.response.overige.soortLead') AS soortLead,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadOmschrijving') AS leadOmschrijving,
    JSON_VALUE(PAYLOAD, '$.response.overige.VestigingID') AS VestigingID,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M', JSON_VALUE(PAYLOAD, '$.response.overige.aangemaaktDatum')) AS aangemaaktDatum,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M',JSON_VALUE(PAYLOAD, '$.response.overige.eersteDeadline')) AS eersteDeadline,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M',JSON_VALUE(PAYLOAD, '$.response.overige.ingezienDatum')) AS ingezienDatum,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M',JSON_VALUE(PAYLOAD, '$.response.overige.eersteContactpoging')) AS eersteContactpoging,
    JSON_VALUE(PAYLOAD, '$.response.overige.medewerkerActieIngezien') AS medewerkerActieIngezien,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalIngezien') AS aantalIngezien,
    JSON_VALUE(PAYLOAD, '$.response.overige.doorlooptijdTotIngezien') AS doorlooptijdTotIngezien,
    JSON_VALUE(PAYLOAD, '$.response.overige.doorlooptijdTotEersteContactpoging') AS doorlooptijdTotEersteContactpoging,
    JSON_VALUE(PAYLOAD, '$.response.overige.doorlooptijdEersteContactpogingBinnenOpvolgtijdenMinuten') AS doorlooptijdEersteContactpogingBinnenOpvolgtijdenMinuten,
    JSON_VALUE(PAYLOAD, '$.response.overige.deadlineGehaald') AS deadlineGehaald,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M',JSON_VALUE(PAYLOAD, '$.response.overige.afgerondDatum')) AS afgerondDatum,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalActiesOpLead') AS aantalActiesOpLead,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalNietBereikt') AS aantalNietBereikt,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalOpnieuwIngepland') AS aantalOpnieuwIngepland,
    JSON_VALUE(PAYLOAD, '$.response.overige.aantalDoorgezet') AS aantalDoorgezet,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.actieGuid') AS actieGuid,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.resultaat') AS resultaat,
    --JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.vestiging') AS laatsteStatus_vestiging,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.VestigingID') AS vestiging_id,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.afgerond') AS laatsteStatus_afgerond,
    --JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.kwalificatie') AS kwalificatie,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.medewerker') AS medewerker,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.voorkeurMedewerker') AS voorkeurMedewerker,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.voorkeurTijdGesprek') AS voorkeurTijdGesprek,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.deadline') AS deadline,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M',JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.startGesprek')) AS laatsteStatus_startGesprek,
    PARSE_DATETIME('%Y-%m-%dT%H:%M:%E*S+%H:%M',JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.eindGesprek')) AS laatsteStatus_eindGesprek,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteStatus.gespreksduurMin') AS gespreksduurMin,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadResultaten[0].Omschrijving') AS afsluitreden,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadResultaten[0].Opmerking') AS afsluitreden_opmerking,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadResultaten[0].DatumVan') AS leadresultaat_datumVan,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadResultaten[0].DatumTot') AS leadresultaat_datumTot,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadResultaten[0].Verkoper') AS leadresultaat_verkoper,
    JSON_VALUE(PAYLOAD, '$.response.overige.leadResultaten[0].Vestiging') AS leadresultaat_vestiging,
    JSON_VALUE(PAYLOAD, '$.response.overige.heeftOfferte') AS heeftOfferte,
    JSON_VALUE(PAYLOAD, '$.response.overige.heeftOrder') AS heeftOrder,
    JSON_VALUE(PAYLOAD, '$.response.overige.ordernummer') AS ordernummer,
    JSON_VALUE(PAYLOAD, '$.response.overige.dealernummer') AS dealernummer,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Kenteken') AS huidigKenteken,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Merk') AS huidigMerk,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Model') AS huidigModel,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.BrandstofType') AS huidigBrandstof,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Uitvoering') AS huidigUitvoering,
    JSON_VALUE(PAYLOAD, '$.response.overige.HuidigVoertuig.Bouwjaar') AS huidigBouwjaar,
    JSON_VALUE(PAYLOAD, '$.response.overige.laatsteMutatieDatum') AS laatsteMutatieDatum,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Vestiging') AS AfspraakDetails_Vestiging,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Afspraakdatum') AS AfspraakDetails_Afspraakdatum,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Tijdstip') AS AfspraakDetails_Tijdstip,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Brengtijd') AS AfspraakDetails_Brengtijd,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Hoofdwerkzaamheid') AS AfspraakDetails_Hoofdwerkzaamheid,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Extra_werkzaamheden') AS AfspraakDetails_Extra_werkzaamheden,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Wachter') AS AfspraakDetails_Wachter,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Vervangend_vervoer') AS AfspraakDetails_Vervangend_vervoer,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.AfspraakId') AS AfspraakDetails_AfspraakId,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Opmerking') AS AfspraakDetails_Opmerking,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Source') AS AfspraakDetails_Source,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.AfspraakDetails.Partner') AS AfspraakDetails_Partner,
    JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Autogegevens.Kilometerstand') AS Autogegevens_Kilometerstand,
    JSON_VALUE(PAYLOAD, '$.response.leadID') AS leadID,
    JSON_VALUE(PAYLOAD, '$.response.bron') AS bron,
    JSON_VALUE(PAYLOAD, '$.response.systeem') AS systeem,
    JSON_VALUE(PAYLOAD, '$.response.vestiging') AS vestiging,
    JSON_VALUE(PAYLOAD, '$.response.eersteKwalificatie') AS kwalificatie,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.relatieType') AS relatieType,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.voornaam') AS voornaam,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.voorletters') AS voorletters,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.tussenvoegsel') AS tussenvoegsel,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.achternaam') AS achternaam,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.geslachtType') AS geslachtType,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.bedrijfsnaam') AS bedrijfsnaam,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.adressen[0].adresType') AS adresType,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.adressen[0].straat') AS straat,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.adressen[0].heeftVoorkeur') AS adres_heeftVoorkeur,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.adressen[0].postcode') AS postcode,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.adressen[0].huisnummer') AS huisnummer,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.adressen[0].huisnummertoevoeging') AS huisnummertoevoeging,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.adressen[0].plaats') AS plaats,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.adressen[0].land') AS land,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[0].contactwijzeType') AS klantInfo_contactwijzen_contactwijzeType,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[0].value') AS klantInfo_contactwijzen_value,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[0].heeftVoorkeur') AS klantInfo_contactwijzen_heeftVoorkeur,
    IF(JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[0].contactwijzeType') = 'E-mail',
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[0].value'), NULL) as email_1,
    IF(JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[0].contactwijzeType') IN ('Mobiel', 'Telefoon', 'TelefoonWerk'),
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[0].value'), NULL) as telefoon_1,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[1].contactwijzeType') AS klantInfo_contactwijzen_contactwijzeType_1,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[1].value') AS klantInfo_contactwijzen_value_1,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[1].heeftVoorkeur') AS klantInfo_contactwijzen_heeftVoorkeur_1,
    IF(JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[1].contactwijzeType') = 'E-mail',
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[1].value'), NULL) as email_2,
    IF(JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[1].contactwijzeType') IN ('Mobiel', 'Telefoon', 'TelefoonWerk'),
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[1].value'), NULL) as telefoon_2,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[2].contactwijzeType') AS klantInfo_contactwijzen_contactwijzeType_2,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[2].value') AS klantInfo_contactwijzen_value_2,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[2].heeftVoorkeur') AS klantInfo_contactwijzen_heeftVoorkeur_2,
    IF(JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[2].contactwijzeType') = 'E-mail',
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[2].value'), NULL) as email_3,
    IF(JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[2].contactwijzeType') IN ('Mobiel', 'Telefoon', 'TelefoonWerk'),
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.contactwijzen[2].value'), NULL) as telefoon_3,
    JSON_VALUE(PAYLOAD, '$.response.klantInfo.bewaartermijn') AS klantInfo_bewaartermijn,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Merk') AS gewenstMerk,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Model') AS gewenstModel,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Uitvoering') AS gewenstUitvoering,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Kenteken') AS gewenstKenteken,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.BrandstofType') AS gewenstBrandstof,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.AutoSoort') AS gewenstAutoSoort,
    JSON_VALUE(PAYLOAD, '$.response.GewenstVoertuig.Bouwjaar') AS gewenstBouwjaar,
    REGEXP_EXTRACT(
    IF
    (JSON_VALUE(PAYLOAD, '$.response.google_clientid') <> '', JSON_VALUE(PAYLOAD, '$.response.google_clientid'),
    IF
      (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.OverigeVelden.google_clientid') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.OverigeVelden.google_clientid'),
      IF
        (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Voertuig Informatie.ClientID') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Voertuig Informatie.ClientID'),
        IF
          (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Informatie.ClientID') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Informatie.ClientID'),
          IF
            (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Extra.ClientID') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Extra.ClientID'),
            IF
              (JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Overige formulier velden.google_clientid') <> '', JSON_VALUE(PAYLOAD, '$.response.overige.extraInfo.Overige formulier velden.google_clientid'), NULL) ) ) ) ) ), '\\d{1,}.\\d{1,}$') 
    AS google_clientid,
    RECEIVEDON,
    ACTION

FROM
    ${ref("df_rawdata_views", "lefBiDataProducer_lasttransaction")}
`
let refs = getRefs()
module.exports = {query, refs}
