
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT 
OFFERTEVTR_DTCMEDIA_CRM_ID,
OFFERTEVTR_OFFERTEID,
SUM(OFFERTEVTR_STREEFMARGEBEDRAG) AS OFFERTEVTR_STREEFMARGEBEDRAG,
SUM(OFFERTEVTR_BRUTOMARGEBEDRAG) AS OFFERTEVTR_BRUTOMARGEBEDRAG,
SUM(OFFERTEVTR_TRANSACTIERESULTAAT) AS OFFERTEVTR_TRANSACTIERESULTAAT,
SUM(OFFERTEVTR_TRANSACTIERUIMTE) AS OFFERTEVTR_TRANSACTIERUIMTE,
SUM(OFFERTEVTR_KORTING) AS OFFERTEVTR_KORTING,
AVG(OFFERTEVTR_ACCESSOIRESPERCENTAGE) AS OFFERTEVTR_ACCESSOIRESPERCENTAGE,
SUM(OFFERTEVTR_MARGEACCESSOIRESBEDRAG) AS OFFERTEVTR_MARGEACCESSOIRESBEDRAG,
MAX(OFFERTEVTR_ISLEASE) AS OFFERTEVTR_ISLEASE

FROM(
SELECT
        JSON_VALUE(PAYLOAD, '$.OFFERTEVTRID') as OFFERTEVTR_OFFERTEVTRID,
        JSON_VALUE(PAYLOAD, '$.OFFERTEID') as OFFERTEVTR_OFFERTEID,
        
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.STREEFMARGEBEDRAG'), "") AS FLOAT64) as OFFERTEVTR_STREEFMARGEBEDRAG,
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.BRUTOMARGEBEDRAG'), "") AS FLOAT64) as OFFERTEVTR_BRUTOMARGEBEDRAG,
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.TRANSACTIERESULTAAT'), "") AS FLOAT64) as OFFERTEVTR_TRANSACTIERESULTAAT,
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.TRANSACTIERUIMTE'), "") AS FLOAT64) as OFFERTEVTR_TRANSACTIERUIMTE,
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.KORTING'), "") AS FLOAT64) as OFFERTEVTR_KORTING,
        
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.ACCESSOIRESPERCENTAGE'), "") AS FLOAT64) as OFFERTEVTR_ACCESSOIRESPERCENTAGE,
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.MARGEACCESSOIRESBEDRAG'), "") AS FLOAT64) as OFFERTEVTR_MARGEACCESSOIRESBEDRAG,
        
        JSON_VALUE(PAYLOAD, '$.ISLEASE') as OFFERTEVTR_ISLEASE,
        JSON_VALUE(PAYLOAD, '$.DTCMEDIA_CRM_ID') as OFFERTEVTR_DTCMEDIA_CRM_ID
        
FROM (
  SELECT MAX(SCHEMA), PRIMARYFIELDHASH, MAX(PAYLOAD) as PAYLOAD, MAX(ACTION) as ACTION, MAX(RECEIVEDON) as RECEIVEDON
    FROM
       ${ref("sam_data_producer_last_transaction")} as first
       WHERE SCHEMA IN (SELECT schema FROM ${ref("sam_table_hashes")} WHERE tableName = 'OFFERTEVTR')
       AND RECEIVEDON = (
          SELECT MAX(RECEIVEDON)
          FROM ${ref("sam_data_producer_last_transaction")} as second
          WHERE first.PRIMARYFIELDHASH = second.PRIMARYFIELDHASH and first.SCHEMA = second.SCHEMA)
      GROUP BY PRIMARYFIELDHASH
))
GROUP BY
OFFERTEVTR_DTCMEDIA_CRM_ID,
OFFERTEVTR_OFFERTEID
`
let refs = pk.getRefs()
module.exports = {query, refs}
