
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `

SELECT
            JSON_VALUE(PAYLOAD, '$.OFFERTEID') as OFFERTE_OFFERTEID,
            JSON_VALUE(PAYLOAD, '$.TRAJECTID') as OFFERTE_TRAJECTID,
            JSON_VALUE(PAYLOAD, '$.OFFERTESTATUSID') as OFFERTE_OFFERTESTATUSID,
            JSON_VALUE(PAYLOAD, '$.DEALERID') as OFFERTE_DEALERID,
            JSON_VALUE(PAYLOAD, '$.VERKOPERID') as OFFERTE_VERKOPERID,
            JSON_VALUE(PAYLOAD, '$.RELATIEID') as OFFERTE_RELATIEID,
            JSON_VALUE(PAYLOAD, '$.ISZAKELIJK') as OFFERTE_ISZAKELIJK,
            JSON_VALUE(PAYLOAD, '$.AUTOMERKID') as OFFERTE_AUTOMERKID,
            JSON_VALUE(PAYLOAD, '$.AFLEVERINGMODELID') as OFFERTE_AFLEVERINGMODELID,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.INRUILBEDRAG'), "") AS FLOAT64) as INRUILBEDRAG,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.KORTING'), "") AS FLOAT64) as KORTING,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.TOTAALBEDRAG'), "") AS FLOAT64) as OFFERTE_TOTAALBEDRAG,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.TOTAALBEDRAGBTW'), "") AS FLOAT64) as TOTAALBEDRAGBTW,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.TOTAALBEDRAGBPM'), "") AS FLOAT64) as TOTAALBEDRAGBPM,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOOMZETCONSUMENT'), "") AS FLOAT64) as AUTOOMZETCONSUMENT,
            
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOOMZETBTW'), "") AS FLOAT64) as AUTOOMZETBTW,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOOMZETBPM'), "") AS FLOAT64) as AUTOOMZETBPM,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOAANGEPASTPRIJSCONSUMENT'), "") AS FLOAT64) as AUTOAANGEPASTPRIJSCONSUMENT,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOAANGEPASTRIJKLAAR'), "") AS FLOAT64) as AUTOAANGEPASTRIJKLAAR,
            
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOAANGEPASTEXBTWPRIJS'), "") AS FLOAT64) as AUTOAANGEPASTEXBTWPRIJS,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOAANGEPASTBRUTOPRIJS'), "") AS FLOAT64) as AUTOAANGEPASTBRUTOPRIJS,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOAANGEPASTNETTOPRIJS'), "") AS FLOAT64) as AUTOAANGEPASTNETTOPRIJS,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOAANGEPASTBTWPRIJS'), "") AS FLOAT64) as AUTOAANGEPASTBTWPRIJS,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOAANGEPASTBPMPRIJS'), "") AS FLOAT64) as AUTOAANGEPASTBPMPRIJS,

            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOPRIJSCONSUMENT'), "") AS FLOAT64) as AUTOPRIJSCONSUMENT,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOPRIJSBTW'), "") AS FLOAT64) as AUTOPRIJSBTW,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTOPRIJSBPM'), "") AS FLOAT64) as AUTOPRIJSBPM,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTORIJKLAAR'), "") AS FLOAT64) as AUTORIJKLAAR,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AUTORIJKLAARDEALER'), "") AS FLOAT64) as AUTORIJKLAARDEALER,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.NETTOCATPRIJS'), "") AS FLOAT64) as NETTOCATPRIJS,
            
            JSON_VALUE(PAYLOAD, '$.DTCMEDIA_CRM_ID') as OFFERTE_DTCMEDIA_CRM_ID,
            CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.DATUMOFFERTE'), "") AS DATE) as OFFERTE_DATUMOFFERTE,
            JSON_VALUE(PAYLOAD, '$.ISLEASEMAATSCHAPPIJ') as OFFERTE_ISLEASEMAATSCHAPPIJ,
            JSON_VALUE(PAYLOAD, '$.AUTOMODELID') as OFFERTE_AUTOMODELID,
            JSON_VALUE(PAYLOAD, '$.AUTOMODELOMSCHRIJVING') as OFFERTE_AUTOMODELOMSCHRIJVING,
            JSON_VALUE(PAYLOAD, '$.GARANTIE') as OFFERTE_GARANTIE,
            JSON_VALUE(PAYLOAD, '$.AUTOMERKCODE') as OFFERTE_AUTOMERKCODE,
            JSON_VALUE(PAYLOAD, '$.AUTOMODELCODE') as OFFERTE_AUTOMODELCODE,
            JSON_VALUE(PAYLOAD, '$.OCCASIONID') as OFFERTE_OCCASIONID,
            JSON_VALUE(PAYLOAD, '$.INRUILOCCASIONID') as OFFERTE_INRUILOCCASIONID
      FROM (
        SELECT MAX(SCHEMA), PRIMARYFIELDHASH, MAX(PAYLOAD) as PAYLOAD, MAX(ACTION) as ACTION, MAX(RECEIVEDON) as RECEIVEDON
          FROM
            ${ref("samDataProducer_lasttransaction")} as first
           WHERE SCHEMA IN (SELECT schema FROM ${ref("sam_table_hashes")} WHERE tableName = 'OFFERTE')
           AND RECEIVEDON = (
              SELECT MAX(RECEIVEDON)
              FROM ${ref("samDataProducer_lasttransaction")} as second
              WHERE first.PRIMARYFIELDHASH = second.PRIMARYFIELDHASH and first.SCHEMA = second.SCHEMA)
          GROUP BY PRIMARYFIELDHASH
      )
      

`
let refs = pk.getRefs()
module.exports = {query, refs}
