
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT
        JSON_VALUE(PAYLOAD, '$.RELATIEID') as RELATIE_RELATIEID,
        JSON_VALUE(PAYLOAD, '$.SOORTRELATIEID') as RELATIE_SOORTRELATIEID,
        JSON_VALUE(PAYLOAD, '$.ACHTERNAAM') as RELATIE_ACHTERNAAM,
        JSON_VALUE(PAYLOAD, '$.TUSSENVOEGSELS') as RELATIE_TUSSENVOEGSELS,
        JSON_VALUE(PAYLOAD, '$.VOORLETTERS') as RELATIE_VOORLETTERS,
        JSON_VALUE(PAYLOAD, '$.VOORNAAM') as RELATIE_VOORNAAM,
        JSON_VALUE(PAYLOAD, '$.GEBOORTEDATUM') as RELATIE_GEBOORTEDATUM,
        JSON_VALUE(PAYLOAD, '$.GESLACHT') as RELATIE_GESLACHT,
        JSON_VALUE(PAYLOAD, '$.EMAIL') as RELATIE_EMAIL,
        JSON_VALUE(PAYLOAD, '$.EMAILOPTIN') as RELATIE_EMAILOPTIN,
        JSON_VALUE(PAYLOAD, '$.TEL1') as RELATIE_TEL1,
        JSON_VALUE(PAYLOAD, '$.TEL1SOORTID') as RELATIE_TEL1SOORTID,
        JSON_VALUE(PAYLOAD, '$.TEL1OPTIN') as RELATIE_TEL1OPTIN,
        JSON_VALUE(PAYLOAD, '$.TEL2') as RELATIE_TEL2,
        JSON_VALUE(PAYLOAD, '$.TEL2SOORTID') as RELATIE_TEL2SOORTID,
        JSON_VALUE(PAYLOAD, '$.TEL2OPTIN') as RELATIE_TEL2OPTIN,
        JSON_VALUE(PAYLOAD, '$.TEL3') as RELATIE_TEL3,
        JSON_VALUE(PAYLOAD, '$.TEL3SOORTID') as RELATIE_TEL3SOORTID,
        JSON_VALUE(PAYLOAD, '$.TEL3OPTIN') as RELATIE_TEL3OPTIN,
        
        JSON_VALUE(PAYLOAD, '$.ACTIEF') as RELATIE_ACTIEF,
        JSON_VALUE(PAYLOAD, '$.ONTDUBBEL') as RELATIE_ONTDUBBEL,
        JSON_VALUE(PAYLOAD, '$.KLANTTYPE') as RELATIE_KLANTTYPE,
        
        JSON_VALUE(PAYLOAD, '$.HEEFTOPENACTIE') as RELATIE_HEEFTOPENACTIE,
        JSON_VALUE(PAYLOAD, '$.HEEFTOPENTRAJECT') as RELATIE_HEEFTOPENTRAJECT,
        JSON_VALUE(PAYLOAD, '$.DATUMMUTATIE') as RELATIE_DATUMMUTATIE,
        JSON_VALUE(PAYLOAD, '$.TELEFOONCONTACT') as RELATIE_TELEFOONCONTACT,
        JSON_VALUE(PAYLOAD, '$.EMAILCONTACT') as RELATIE_EMAILCONTACT,
        JSON_VALUE(PAYLOAD, '$.POSTCONTACT') as RELATIE_POSTCONTACT,        
                
        JSON_VALUE(PAYLOAD, '$.OVERLEDEN') as RELATIE_OVERLEDEN,
        JSON_VALUE(PAYLOAD, '$.EMAILZAKELIJK') as RELATIE_EMAILZAKELIJK,
        JSON_VALUE(PAYLOAD, '$.EMAILZAKELIJKOPTIN') as RELATIE_EMAILZAKELIJKOPTIN,
        JSON_VALUE(PAYLOAD, '$.EINDDATUM') as RELATIE_EINDDATUM,
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AANMAAKDATUM'), "") AS DATETIME) as RELATIE_AANMAAKDATUM,
        JSON_VALUE(PAYLOAD, '$.DTCMEDIA_CRM_ID') as RELATIE_DTCMEDIA_CRM_ID,
        JSON_VALUE(PAYLOAD, '$.DEALERID') as RELATIE_DEALERID

FROM (
  SELECT MAX(SCHEMA), PRIMARYFIELDHASH, MAX(PAYLOAD) as PAYLOAD, MAX(ACTION) as ACTION, MAX(RECEIVEDON) as RECEIVEDON
    FROM
       ${ref("samDataProducer_lasttransaction")} as first
       WHERE SCHEMA IN (SELECT schema FROM ${ref("sam_table_hashes")} WHERE tableName = 'RELATIE')
       AND RECEIVEDON = (
          SELECT MAX(RECEIVEDON)
          FROM ${ref("samDataProducer_lasttransaction")} as second
          WHERE first.PRIMARYFIELDHASH = second.PRIMARYFIELDHASH and first.SCHEMA = second.SCHEMA)
      GROUP BY PRIMARYFIELDHASH
)


`
let refs = pk.getRefs()
module.exports = {query, refs}
