
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT 
OFFERTEVTR_DTCMEDIA_CRM_ID,
OFFERTEVTR_OFFERTEID,
SUM(OFFERTEVTR_STREEFMARGEBEDRAG) AS OFFERTEVTR_STREEFMARGEBEDRAG,
SUM(OFFERTEVTR_BRUTOMARGEBEDRAG) AS OFFERTEVTR_BRUTOMARGEBEDRAG,
SUM(OFFERTEVTR_TRANSACTIERESULTAAT) AS OFFERTEVTR_TRANSACTIERESULTAAT,
SUM(OFFERTEVTR_TRANSACTIERUIMTE) AS OFFERTEVTR_TRANSACTIERUIMTE,
SUM(OFFERTEVTR_KORTING) AS OFFERTEVTR_KORTING,
AVG(OFFERTEVTR_ACCESSOIRESPERCENTAGE) AS OFFERTEVTR_ACCESSOIRESPERCENTAGE,
SUM(OFFERTEVTR_MARGEACCESSOIRESBEDRAG) AS OFFERTEVTR_MARGEACCESSOIRESBEDRAG,
MAX(OFFERTEVTR_ISLEASE) AS OFFERTEVTR_ISLEASE

FROM(
SELECT
  JSON_VALUE(PAYLOAD, '$.offertevtrid') AS OFFERTEVTR_OFFERTEVTRID,
  JSON_VALUE(PAYLOAD, '$.response.offerteid') AS OFFERTEVTR_OFFERTEID,
  CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.response.streefmargebedrag'), "") AS FLOAT64) AS OFFERTEVTR_STREEFMARGEBEDRAG,
  CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.response.brutomargebedrag'), "") AS FLOAT64) AS OFFERTEVTR_BRUTOMARGEBEDRAG,
  CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.response.transactieresultaat'), "") AS FLOAT64) AS OFFERTEVTR_TRANSACTIERESULTAAT,
  CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.response.transactieruimte'), "") AS FLOAT64) AS OFFERTEVTR_TRANSACTIERUIMTE,
  CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.response.korting'), "") AS FLOAT64) AS OFFERTEVTR_KORTING,
  CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.response.accessoirespercentage'), "") AS FLOAT64) AS OFFERTEVTR_ACCESSOIRESPERCENTAGE,
  CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.response.margeaccessoiresbedrag'), "") AS FLOAT64) AS OFFERTEVTR_MARGEACCESSOIRESBEDRAG,
  JSON_VALUE(PAYLOAD, '$.response.islease') AS OFFERTEVTR_ISLEASE,
  JSON_VALUE(PAYLOAD, '$.dtcmedia_crm_id') AS OFFERTEVTR_DTCMEDIA_CRM_ID
        
FROM ${ref("odbcDataProducer_lasttransaction")}
      WHERE PUBLISHER = "SAMOfferteVTRPublisher" 
)
GROUP BY
OFFERTEVTR_DTCMEDIA_CRM_ID,
OFFERTEVTR_OFFERTEID
`
let refs = pk.getRefs()
module.exports = {query, refs}
