
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `


SELECT
ADRES_RELATIEID,
ADRES_DTCMEDIA_CRM_ID,
MAX(ADRES_ADRESID) as ADRES_ADRESID,
MAX(ADRES_SOORTADRESID) as ADRES_SOORTADRESID,

MAX(ADRES_HUISNUMMER) as ADRES_HUISNUMMER,
MAX(ADRES_HUISNRTOEVOEGING) as ADRES_HUISNRTOEVOEGING,
MAX(ADRES_POSTCODE) as ADRES_POSTCODE,
MAX(ADRES_ISSTANDAARD) as ADRES_ISSTANDAARD,

MAX(ADRES_STRAAT) as ADRES_STRAAT,
MAX(ADRES_PLAATS) as ADRES_PLAATS,
MAX(ADRES_LAND) as ADRES_LAND,
MAX(ADRES_ACTIEF) as ADRES_ACTIEF

FROM (
      SELECT
          JSON_VALUE(PAYLOAD, '$.ADRESID') as ADRES_ADRESID,
          JSON_VALUE(PAYLOAD, '$.RELATIEID') as ADRES_RELATIEID,
          JSON_VALUE(PAYLOAD, '$.SOORTADRESID') as ADRES_SOORTADRESID,
          
          JSON_VALUE(PAYLOAD, '$.STRAAT') as ADRES_STRAAT,
          JSON_VALUE(PAYLOAD, '$.HUISNUMMER') as ADRES_HUISNUMMER,
          JSON_VALUE(PAYLOAD, '$.HUISNRTOEVOEGING') as ADRES_HUISNRTOEVOEGING,
          JSON_VALUE(PAYLOAD, '$.POSTCODE') as ADRES_POSTCODE,
          JSON_VALUE(PAYLOAD, '$.PLAATS') as ADRES_PLAATS,
          JSON_VALUE(PAYLOAD, '$.LAND') as ADRES_LAND,
          
          JSON_VALUE(PAYLOAD, '$.ISSTANDAARD') as ADRES_ISSTANDAARD,
          JSON_VALUE(PAYLOAD, '$.ACTIEF') as ADRES_ACTIEF,
          JSON_VALUE(PAYLOAD, '$.DTCMEDIA_CRM_ID') as ADRES_DTCMEDIA_CRM_ID
      FROM (
       SELECT MAX(SCHEMA), PRIMARYFIELDHASH, MAX(PAYLOAD) as PAYLOAD, MAX(ACTION) as ACTION, MAX(RECEIVEDON) as RECEIVEDON
          FROM
            ${ref("samDataProducer_lasttransaction")} as first
           WHERE SCHEMA IN (SELECT schema FROM ${ref("sam_table_hashes")} WHERE tableName = 'ADRES')
           AND RECEIVEDON = (
              SELECT MAX(RECEIVEDON)
              FROM ${ref("samDataProducer_lasttransaction")} as second
              WHERE first.PRIMARYFIELDHASH = second.PRIMARYFIELDHASH and first.SCHEMA = second.SCHEMA)
          GROUP BY PRIMARYFIELDHASH
      )
)

WHERE ADRES_ISSTANDAARD = "T" AND ADRES_ACTIEF = 'T'
GROUP BY ADRES_RELATIEID, ADRES_DTCMEDIA_CRM_ID
`
let refs = pk.getRefs()
module.exports = {query, refs}
