
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT 
RELATIEOPTIN_DTCMEDIA_CRM_ID,
RELATIEOPTIN_RELATIEID,
MAX(RELATIEOPTIN_BRON) AS RELATIEOPTIN_BRON,
MAX(RELATIEOPTIN_DATUMTIJD) AS RELATIEOPTIN_DATUMTIJD,
MAX(IF(RELATIEOPTIN_SOORT = '1', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfAutoTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '2', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfAutoEmail,
MAX(IF(RELATIEOPTIN_SOORT = '3', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfAutoMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '4', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfAutoPost,
MAX(IF(RELATIEOPTIN_SOORT = '5', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfMerkModelTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '6', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfMerkModelEmail,
MAX(IF(RELATIEOPTIN_SOORT = '7', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfMerkModelMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '8', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfMerkModelPost,

MAX(IF(RELATIEOPTIN_SOORT = '9', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfBedrijfTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '10', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfBedrijfEmail,
MAX(IF(RELATIEOPTIN_SOORT = '11', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfBedrijfMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '12', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfBedrijfPost,
MAX(IF(RELATIEOPTIN_SOORT = '13', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfOverigeTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '14', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfOverigeEmail,
MAX(IF(RELATIEOPTIN_SOORT = '15', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfOverigeMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '16', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfOverigePost,

MAX(IF(RELATIEOPTIN_SOORT = '17', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfEnquetesTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '18', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfEnquetesEmail,
MAX(IF(RELATIEOPTIN_SOORT = '19', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfEnquetesMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '20', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfEnquetesPost,
MAX(IF(RELATIEOPTIN_SOORT = '21', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepAutoTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '22', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepAutoEmail,
MAX(IF(RELATIEOPTIN_SOORT = '23', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepAutoMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '24', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepAutoPost,

MAX(IF(RELATIEOPTIN_SOORT = '25', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepMerkModelTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '26', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepMerkModelEmail,
MAX(IF(RELATIEOPTIN_SOORT = '27', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepMerkModelMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '28', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepMerkModelPost,
MAX(IF(RELATIEOPTIN_SOORT = '29', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepBedrijfTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '30', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepBedrijfEmail,
MAX(IF(RELATIEOPTIN_SOORT = '31', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepBedrijfMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '32', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepBedrijfPost,

MAX(IF(RELATIEOPTIN_SOORT = '33', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepOverigeTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '34', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepOverigeEmail,
MAX(IF(RELATIEOPTIN_SOORT = '35', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepOverigeMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '36', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepOverigePost,
MAX(IF(RELATIEOPTIN_SOORT = '37', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepEnquetesTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '38', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepEnquetesEmail,
MAX(IF(RELATIEOPTIN_SOORT = '39', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepEnquetesMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '40', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepEnquetesPost,

MAX(IF(RELATIEOPTIN_SOORT = '41', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurAutoTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '42', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurAutoEmail,
MAX(IF(RELATIEOPTIN_SOORT = '43', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurAutoMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '44', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurAutoPost,
MAX(IF(RELATIEOPTIN_SOORT = '45', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurMerkModelTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '46', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurMerkModelEmail,
MAX(IF(RELATIEOPTIN_SOORT = '47', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurMerkModelMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '48', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurMerkModelPost,

MAX(IF(RELATIEOPTIN_SOORT = '49', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurBedrijfTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '50', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurBedrijfEmail,
MAX(IF(RELATIEOPTIN_SOORT = '51', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurBedrijfMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '52', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurBedrijfPost,
MAX(IF(RELATIEOPTIN_SOORT = '53', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurOverigeTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '54', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurOverigeEmail,
MAX(IF(RELATIEOPTIN_SOORT = '55', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurOverigeMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '56', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurOverigePost,

MAX(IF(RELATIEOPTIN_SOORT = '57', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurEnquetesTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '58', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurEnquetesEmail,
MAX(IF(RELATIEOPTIN_SOORT = '59', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurEnquetesMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '60', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurEnquetesPost,
MAX(IF(RELATIEOPTIN_SOORT = '61', RELATIEOPTIN_OPTIN, NULL)) AS OverigeAutoTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '62', RELATIEOPTIN_OPTIN, NULL)) AS OverigeAutoEmail,
MAX(IF(RELATIEOPTIN_SOORT = '63', RELATIEOPTIN_OPTIN, NULL)) AS OverigeAutoMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '64', RELATIEOPTIN_OPTIN, NULL)) AS OverigeAutoPost,

MAX(IF(RELATIEOPTIN_SOORT = '65', RELATIEOPTIN_OPTIN, NULL)) AS OverigeMerkModelTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '66', RELATIEOPTIN_OPTIN, NULL)) AS OverigeMerkModelEmail,
MAX(IF(RELATIEOPTIN_SOORT = '67', RELATIEOPTIN_OPTIN, NULL)) AS OverigeMerkModelMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '68', RELATIEOPTIN_OPTIN, NULL)) AS OverigeMerkModelPost,
MAX(IF(RELATIEOPTIN_SOORT = '69', RELATIEOPTIN_OPTIN, NULL)) AS OverigeBedrijfTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '70', RELATIEOPTIN_OPTIN, NULL)) AS OverigeBedrijfEmail,
MAX(IF(RELATIEOPTIN_SOORT = '71', RELATIEOPTIN_OPTIN, NULL)) AS OverigeBedrijfMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '72', RELATIEOPTIN_OPTIN, NULL)) AS OverigeBedrijfPost,

MAX(IF(RELATIEOPTIN_SOORT = '73', RELATIEOPTIN_OPTIN, NULL)) AS OverigeOverigeTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '74', RELATIEOPTIN_OPTIN, NULL)) AS OverigeOverigeEmail,
MAX(IF(RELATIEOPTIN_SOORT = '75', RELATIEOPTIN_OPTIN, NULL)) AS OverigeOverigeMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '76', RELATIEOPTIN_OPTIN, NULL)) AS OverigeOverigePost,
MAX(IF(RELATIEOPTIN_SOORT = '77', RELATIEOPTIN_OPTIN, NULL)) AS OverigeEnquetesTelefoon,
MAX(IF(RELATIEOPTIN_SOORT = '78', RELATIEOPTIN_OPTIN, NULL)) AS OverigeEnquetesEmail,
MAX(IF(RELATIEOPTIN_SOORT = '79', RELATIEOPTIN_OPTIN, NULL)) AS OverigeEnquetesMessenger,
MAX(IF(RELATIEOPTIN_SOORT = '80', RELATIEOPTIN_OPTIN, NULL)) AS OverigeEnquetesPost,

FROM( 
SELECT 
*,
ROW_NUMBER() OVER(PARTITION BY RELATIEOPTIN_DTCMEDIA_CRM_ID, RELATIEOPTIN_RELATIEID, RELATIEOPTIN_SOORT ORDER BY RELATIEOPTIN_DATUMTIJD DESC) AS optin_rank

FROM ${ref("df_rawdata_views", "sam_relatieoptin")})
--WHERE RELATIEOPTIN_DTCMEDIA_CRM_ID = "53")

WHERE optin_rank = 1
GROUP BY
RELATIEOPTIN_DTCMEDIA_CRM_ID,
RELATIEOPTIN_RELATIEID

`
let refs = pk.getRefs()
module.exports = {query, refs}
