
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT 
RELATIEOPTIN_DTCMEDIA_CRM_ID,
RELATIEOPTIN_RELATIEID,
MAX(RELATIEOPTIN_BRON) AS RELATIEOPTIN_BRON,
MAX(RELATIEOPTIN_DATUMTIJD) AS RELATIEOPTIN_DATUMTIJD,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '1', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfAutoTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '2', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfAutoEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '3', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfAutoMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '4', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfAutoPost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '5', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfMerkModelTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '6', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfMerkModelEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '7', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfMerkModelMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '8', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfMerkModelPost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '9', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfBedrijfTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '10', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfBedrijfEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '11', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfBedrijfMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '12', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfBedrijfPost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '13', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfOverigeTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '14', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfOverigeEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '15', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfOverigeMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '16', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfOverigePost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '17', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfEnquetesTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '18', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfEnquetesEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '19', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfEnquetesMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '20', RELATIEOPTIN_OPTIN, NULL)) AS AutobedrijfEnquetesPost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '21', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepAutoTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '22', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepAutoEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '23', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepAutoMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '24', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepAutoPost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '25', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepMerkModelTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '26', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepMerkModelEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '27', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepMerkModelMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '28', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepMerkModelPost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '29', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepBedrijfTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '30', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepBedrijfEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '31', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepBedrijfMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '32', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepBedrijfPost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '33', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepOverigeTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '34', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepOverigeEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '35', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepOverigeMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '36', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepOverigePost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '37', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepEnquetesTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '38', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepEnquetesEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '39', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepEnquetesMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '40', RELATIEOPTIN_OPTIN, NULL)) AS BedrijfsGroepEnquetesPost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '41', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurAutoTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '42', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurAutoEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '43', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurAutoMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '44', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurAutoPost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '45', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurMerkModelTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '46', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurMerkModelEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '47', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurMerkModelMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '48', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurMerkModelPost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '49', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurBedrijfTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '50', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurBedrijfEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '51', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurBedrijfMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '52', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurBedrijfPost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '53', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurOverigeTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '54', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurOverigeEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '55', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurOverigeMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '56', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurOverigePost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '57', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurEnquetesTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '58', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurEnquetesEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '59', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurEnquetesMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '60', RELATIEOPTIN_OPTIN, NULL)) AS ImporteurEnquetesPost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '61', RELATIEOPTIN_OPTIN, NULL)) AS OverigeAutoTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '62', RELATIEOPTIN_OPTIN, NULL)) AS OverigeAutoEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '63', RELATIEOPTIN_OPTIN, NULL)) AS OverigeAutoMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '64', RELATIEOPTIN_OPTIN, NULL)) AS OverigeAutoPost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '65', RELATIEOPTIN_OPTIN, NULL)) AS OverigeMerkModelTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '66', RELATIEOPTIN_OPTIN, NULL)) AS OverigeMerkModelEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '67', RELATIEOPTIN_OPTIN, NULL)) AS OverigeMerkModelMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '68', RELATIEOPTIN_OPTIN, NULL)) AS OverigeMerkModelPost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '69', RELATIEOPTIN_OPTIN, NULL)) AS OverigeBedrijfTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '70', RELATIEOPTIN_OPTIN, NULL)) AS OverigeBedrijfEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '71', RELATIEOPTIN_OPTIN, NULL)) AS OverigeBedrijfMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '72', RELATIEOPTIN_OPTIN, NULL)) AS OverigeBedrijfPost,

MAX(IF(RELATIEOPTIN_OPTINSOORT = '73', RELATIEOPTIN_OPTIN, NULL)) AS OverigeOverigeTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '74', RELATIEOPTIN_OPTIN, NULL)) AS OverigeOverigeEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '75', RELATIEOPTIN_OPTIN, NULL)) AS OverigeOverigeMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '76', RELATIEOPTIN_OPTIN, NULL)) AS OverigeOverigePost,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '77', RELATIEOPTIN_OPTIN, NULL)) AS OverigeEnquetesTelefoon,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '78', RELATIEOPTIN_OPTIN, NULL)) AS OverigeEnquetesEmail,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '79', RELATIEOPTIN_OPTIN, NULL)) AS OverigeEnquetesMessenger,
MAX(IF(RELATIEOPTIN_OPTINSOORT = '80', RELATIEOPTIN_OPTIN, NULL)) AS OverigeEnquetesPost,

FROM( 
SELECT 
*,
ROW_NUMBER() OVER(PARTITION BY RELATIEOPTIN_DTCMEDIA_CRM_ID, RELATIEOPTIN_RELATIEID, RELATIEOPTIN_OPTINSOORT ORDER BY RELATIEOPTIN_DATUMTIJD DESC) AS optin_rank

FROM ${ref("df_rawdata_views", "sam_relatieoptin")})
--WHERE RELATIEOPTIN_DTCMEDIA_CRM_ID = "53")

WHERE optin_rank = 1
GROUP BY
RELATIEOPTIN_DTCMEDIA_CRM_ID,
RELATIEOPTIN_RELATIEID

`
let refs = pk.getRefs()
module.exports = {query, refs}
