
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT
  JSON_VALUE(PAYLOAD, '$.trajectid') AS TRAJECT_TRAJECTID,
  JSON_VALUE(PAYLOAD, '$.dtcmedia_crm_id') AS TRAJECT_DTCMEDIA_CRM_ID,
  JSON_VALUE(PAYLOAD, '$.type') AS TRAJECT_TYPE,
  JSON_VALUE(PAYLOAD, '$.response.accountid') AS TRAJECT_ACCOUNTID,
  JSON_VALUE(PAYLOAD, '$.response.afgeronddatum') AS TRAJECT_AFGERONDDATUM,
  JSON_VALUE(PAYLOAD, '$.response.aflevergebruikerid') AS TRAJECT_AFLEVERGEBRUIKERID,
  JSON_VALUE(PAYLOAD, '$.response.afsluittoelichting') AS TRAJECT_AFSLUITTOELICHTING,
  JSON_VALUE(PAYLOAD, '$.response.autodatasourceid') AS TRAJECT_AUTODATASOURCEID,
  JSON_VALUE(PAYLOAD, '$.response.autonaamkort') AS TRAJECT_AUTONAAMKORT,
  JSON_VALUE(PAYLOAD, '$.response.autonaamlang') AS TRAJECT_AUTONAAMLANG,
  JSON_VALUE(PAYLOAD, '$.response.bestuurderid') AS TRAJECT_BESTUURDERID,
  JSON_VALUE(PAYLOAD, '$.response.contactgeweest') AS TRAJECT_CONTACTGEWEEST,
  SAFE_CAST(JSON_VALUE(PAYLOAD, '$.response.creatiedatum') AS DATETIME) AS TRAJECT_CREATIEDATUM,
  JSON_VALUE(PAYLOAD, '$.response.dealerid') AS TRAJECT_DEALERID,
  JSON_VALUE(PAYLOAD, '$.response.dealersoortleadsbronid') AS TRAJECT_DEALERSOORTLEADSBRONID,
  JSON_VALUE(PAYLOAD, '$.response.definitiefofferteid') AS TRAJECT_DEFINITIEFOFFERTEID,
  JSON_VALUE(PAYLOAD, '$.response.dmcampagneid') AS TRAJECT_DMCAMPAGNEID,
  JSON_VALUE(PAYLOAD, '$.response.eerstekwalificatie') AS TRAJECT_EERSTEKWALIFICATIE,
  JSON_VALUE(PAYLOAD, '$.response.eersteopvolging') AS TRAJECT_EERSTEOPVOLGING,
  JSON_VALUE(PAYLOAD, '$.response.einddatum') AS TRAJECT_EINDDATUM,
  JSON_VALUE(PAYLOAD, '$.response.einddatumberekend') AS TRAJECT_EINDDATUMBEREKEND,
  JSON_VALUE(PAYLOAD, '$.response.externid') AS TRAJECT_EXTERNID,
  JSON_VALUE(PAYLOAD, '$.response.externleadid') AS TRAJECT_EXTERNLEADID,
  JSON_VALUE(PAYLOAD, '$.response.financieringvoorbeeld') AS TRAJECT_FINANCIERINGVOORBEELD,
  JSON_VALUE(PAYLOAD, '$.response.fleetdealid') AS TRAJECT_FLEETDEALID,
  JSON_VALUE(PAYLOAD, '$.response.garantieaanvraag') AS TRAJECT_GARANTIEAANVRAAG,
  JSON_VALUE(PAYLOAD, '$.response.geopenddatum') AS TRAJECT_GEOPENDDATUM,
  JSON_VALUE(PAYLOAD, '$.response.handelsauto') AS TRAJECT_HANDELSAUTO,
  JSON_VALUE(PAYLOAD, '$.response.herkomstid') AS TRAJECT_HERKOMSTID,
  JSON_VALUE(PAYLOAD, '$.response.ismixedautonaam') AS TRAJECT_ISMIXEDAUTONAAM,
  JSON_VALUE(PAYLOAD, '$.response.ismixedsoortofferte') AS TRAJECT_ISMIXEDSOORTOFFERTE,
  JSON_VALUE(PAYLOAD, '$.response.kwalificatietoegekend') AS TRAJECT_KWALIFICATIETOEGEKEND,
  JSON_VALUE(PAYLOAD, '$.response.leadflags') AS TRAJECT_LEADFLAGS,
  JSON_VALUE(PAYLOAD, '$.response.leadklasseid') AS TRAJECT_LEADKLASSEID,
  JSON_VALUE(PAYLOAD, '$.response.leadsbijlageid') AS TRAJECT_LEADSBIJLAGEID,
  JSON_VALUE(PAYLOAD, '$.response.leadsgroepid') AS TRAJECT_LEADSGROEPID,
  JSON_VALUE(PAYLOAD, '$.response.leadshown') AS TRAJECT_LEADSHOWN,
  JSON_VALUE(PAYLOAD, '$.response.leaseaanvraag') AS TRAJECT_LEASEAANVRAAG,
  JSON_VALUE(PAYLOAD, '$.response.leasemijid') AS TRAJECT_LEASEMIJID,
  JSON_VALUE(PAYLOAD, '$.response.mailingaantal') AS TRAJECT_MAILINGAANTAL,
  JSON_VALUE(PAYLOAD, '$.response.nextactiedatum') AS TRAJECT_NEXTACTIEDATUM,
  JSON_VALUE(PAYLOAD, '$.response.nextactieid') AS TRAJECT_NEXTACTIEID,
  JSON_VALUE(PAYLOAD, '$.response.omschrijving') AS TRAJECT_OMSCHRIJVING,
  JSON_VALUE(PAYLOAD, '$.response.opmerkingen') AS TRAJECT_OPMERKINGEN,
  JSON_VALUE(PAYLOAD, '$.response.opvolgdatum') AS TRAJECT_OPVOLGDATUM,
  JSON_VALUE(PAYLOAD, '$.response.opvolgenvoor') AS TRAJECT_OPVOLGENVOOR,
  JSON_VALUE(PAYLOAD, '$.response.orderwijziging') AS TRAJECT_ORDERWIJZIGING,
  JSON_VALUE(PAYLOAD, '$.response.prevtrajectid') AS TRAJECT_PREVTRAJECTID,
  JSON_VALUE(PAYLOAD, '$.response.relatieid') AS TRAJECT_RELATIEID,
  JSON_VALUE(PAYLOAD, '$.response.soortauto') AS TRAJECT_SOORTAUTO,
  JSON_VALUE(PAYLOAD, '$.response.soortleadsbronid') AS TRAJECT_SOORTLEADSBRONID,
  JSON_VALUE(PAYLOAD, '$.response.soortofferteid') AS TRAJECT_SOORTOFFERTEID,
  JSON_VALUE(PAYLOAD, '$.response.soorttrajectid') AS TRAJECT_SOORTTRAJECTID,
  JSON_VALUE(PAYLOAD, '$.response.sourcetrajectid') AS TRAJECT_SOURCETRAJECTID,
  JSON_VALUE(PAYLOAD, '$.response.startdatum') AS TRAJECT_STARTDATUM,
  JSON_VALUE(PAYLOAD, '$.response.subrelatieid') AS TRAJECT_SUBRELATIEID,
  JSON_VALUE(PAYLOAD, '$.response.toegekenddatum') AS TRAJECT_TOEGEKENDDATUM,
  JSON_VALUE(PAYLOAD, '$.response.trajectafsluitredenid') AS TRAJECT_TRAJECTAFSLUITREDENID,
  JSON_VALUE(PAYLOAD, '$.response.trajectkans') AS TRAJECT_TRAJECTKANS,
  JSON_VALUE(PAYLOAD, '$.response.trajectstatusid') AS TRAJECTSTATUSID,
  JSON_VALUE(PAYLOAD, '$.response.verkoperid') AS TRAJECT_VERKOPERID,
  JSON_VALUE(PAYLOAD, '$.response.verzekeringaanvraag') AS TRAJECT_VERZEKERINGAANVRAAG,

FROM 
${ref("odbcDataProducer_lasttransaction")}
WHERE PUBLISHER = "SAMTrajectsPublisher"

`
let refs = pk.getRefs()
module.exports = {query, refs}
