
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT
        RECEIVEDON,
        ACTION,
        JSON_VALUE(PAYLOAD, '$.DTCMEDIA_CRM_ID') as TRAJECT_DTCMEDIA_CRM_ID,
        JSON_VALUE(PAYLOAD, '$.TRAJECTID') as TRAJECT_TRAJECTID,
        JSON_VALUE(PAYLOAD, '$.RELATIEID') as TRAJECT_RELATIEID,
        JSON_VALUE(PAYLOAD, '$.DEALERID') as TRAJECT_DEALERID,
        JSON_VALUE(PAYLOAD, '$.VERKOPERID') as TRAJECT_VERKOPERID,
        JSON_VALUE(PAYLOAD, '$.AFLEVERGEBRUIKERID') as TRAJECT_AFLEVERGEBRUIKERID,
        JSON_VALUE(PAYLOAD, '$.TRAJECTSTATUSID') as TRAJECTSTATUSID,
        JSON_VALUE(PAYLOAD, '$.SOORTTRAJECTID') as TRAJECT_SOORTTRAJECTID,
        JSON_VALUE(PAYLOAD, '$.TRAJECTAFSLUITREDENID') as TRAJECT_TRAJECTAFSLUITREDENID,
        JSON_VALUE(PAYLOAD, '$.DEFINITIEFOFFERTEID') as TRAJECT_DEFINITIEFOFFERTEID,
        JSON_VALUE(PAYLOAD, '$.PREVTRAJECTID') as TRAJECT_PREVTRAJECTID,
        JSON_VALUE(PAYLOAD, '$.NEXTACTIEDATUM') as TRAJECT_NEXTACTIEDATUM,
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.CREATIEDATUM'), "") AS DATETIME) as TRAJECT_CREATIEDATUM, 
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.STARTDATUM'), "") AS DATE) as TRAJECT_STARTDATUM,
        CAST(NULLIF(JSON_VALUE(PAYLOAD, '$.AFGERONDDATUM'), "") AS DATETIME) as TRAJECT_AFGERONDDATUM, 
        JSON_VALUE(PAYLOAD, '$.EXTERNLEADID') as TRAJECT_EXTERNLEADID,
        JSON_VALUE(PAYLOAD, '$.SOORTAUTO') as TRAJECT_SOORTAUTO,
        JSON_VALUE(PAYLOAD, '$.SOORTOFFERTEID') as TRAJECT_SOORTOFFERTEID,
        JSON_VALUE(PAYLOAD, '$.TRAJECTKANS') as TRAJECT_TRAJECTKANS,
        JSON_VALUE(PAYLOAD, '$.MAILINGAANTAL') as TRAJECT_MAILINGAANTAL,
        JSON_VALUE(PAYLOAD, '$.HANDELSAUTO') as TRAJECT_HANDELSAUTO,
        JSON_VALUE(PAYLOAD, '$.EXTERNID') as TRAJECT_EXTERNID,
        JSON_VALUE(PAYLOAD, '$.OMSCHRIJVING') as TRAJECT_OMSCHRIJVING,
        JSON_VALUE(PAYLOAD, '$.EERSTEKWALIFICATIE') as TRAJECT_EERSTEKWALIFICATIE,
        JSON_VALUE(PAYLOAD, '$.SOORTLEADSBRONID') as TRAJECT_SOORTLEADSBRONID,
        JSON_VALUE(PAYLOAD, '$.LEADKLASSEID') as TRAJECT_LEADKLASSEID,        
        JSON_VALUE(PAYLOAD, '$.NEXTACTIEID') as TRAJECT_NEXTACTIEID,
        JSON_VALUE(PAYLOAD, '$.HERKOMSTID') as TRAJECT_HERKOMSTID,
        JSON_VALUE(PAYLOAD, '$.BESTUURDERID') as TRAJECT_BESTUURDERID,
        JSON_VALUE(PAYLOAD, '$.LEASEMIJID') as TRAJECT_LEASEMIJID,
        JSON_VALUE(PAYLOAD, '$.LEADSGROEPID') as TRAJECT_LEADSGROEPID,        
        JSON_VALUE(PAYLOAD, '$.AUTONAAMKORT') as TRAJECT_AUTONAAMKORT,
        JSON_VALUE(PAYLOAD, '$.AUTONAAMLANG') as TRAJECT_AUTONAAMLANG

FROM (
   SELECT MAX(SCHEMA), PRIMARYFIELDHASH, MAX(PAYLOAD) as PAYLOAD, MAX(ACTION) as ACTION, MAX(RECEIVEDON) as RECEIVEDON
    FROM
      ${ref("df_rawdata_views", "samDataProducer_lasttransaction")} as first
     WHERE SCHEMA IN (SELECT schema FROM ${ref("df_rawdata_views", "sam_table_hashes")} WHERE tableName = 'TRAJECT')
     AND RECEIVEDON = (
        SELECT MAX(RECEIVEDON)
        FROM ${ref("df_rawdata_views", "samDataProducer_lasttransaction")} as second
        WHERE first.PRIMARYFIELDHASH = second.PRIMARYFIELDHASH and first.SCHEMA = second.SCHEMA)
    GROUP BY PRIMARYFIELDHASH
)

`
let refs = pk.getRefs()
module.exports = {query, refs}
