
/*config*/
let pk = require("../../sources")
let ref = pk.ref
let query = `
SELECT
        TRAJECT_TRAJECTID AS AFLEVERTRAJECT_TRAJECTID,
        TRAJECT_RELATIEID AS AFLEVERTRAJECT_RELATIEID,
        TRAJECT_DEALERID AS AFLEVERTRAJECT_DEALERID,
        TRAJECT_VERKOPERID AS AFLEVERTRAJECT_VERKOPERID,
        TRAJECT_AFLEVERGEBRUIKERID AS AFLEVERTRAJECT_AFLEVERGEBRUIKERID,
        TRAJECTSTATUSID AS AFLEVERTRAJECT_TRAJECTSTATUSID,
        TRAJECT_SOORTTRAJECTID AS AFLEVERTRAJECT_SOORTTRAJECTID,
        TRAJECT_DEFINITIEFOFFERTEID AS AFLEVERTRAJECT_DEFINITIEFOFFERTEID,
        TRAJECT_PREVTRAJECTID AS AFLEVERTRAJECT_PREVTRAJECTID,
        TRAJECT_CREATIEDATUM as AFLEVERTRAJECT_CREATIEDATUM,
        TRAJECT_AFGERONDDATUM AS AFLEVERTRAJECT_AFGERONDDATUM,
        TRAJECT_DTCMEDIA_CRM_ID AS AFLEVERTRAJECT_DTCMEDIA_CRM_ID,
        TRAJECT_SOORTAUTO AS AFLEVERTRAJECT_SOORTAUTO
FROM ${ref("df_rawdata_views", "sam_trajects")}
WHERE TRAJECT_SOORTTRAJECTID = '3'

`
let refs = pk.getRefs()
module.exports = {query, refs}
