/*config*/
let pk = require("../../sources")
let sources = pk.getSources().map((s) => s.alias ?? s.name )
let ref = pk.ref
let query = `

WITH
  sequences AS(
  SELECT
    account,
    JSON_VALUE(PAYLOAD, '$.pk_crm_id') AS pk_crm_id,
    JSON_VALUE(PAYLOAD, '$.submission_id') AS submission_id,
    JSON_VALUE(PAYLOAD, '$.submission.id') AS submission_id_in_submission,
    JSON_VALUE(PAYLOAD, '$.submission.taxation_module_id') AS taxation_module_id,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.leadSource') AS leadSource,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.leadType') AS leadType,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarBrand') AS buyCarBrand,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarModel') AS buyCarModel,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarType') AS buyCarType,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarEngine') AS buyCarEngine,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarPriceList') AS buyCarPriceList,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarTestDrive') AS buyCarTestDrive,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarBrochure') AS buyCarBrochure,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarPrice') AS buyCarPrice,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarImage') AS buyCarImage,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarTaxationMailHeaderImage') AS buyCarTaxationMailHeaderImage,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarTaxationPdfHeaderImage') AS buyCarTaxationPdfHeaderImage,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarExtraTradeInValue') AS buyCarExtraTradeInValue,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarDealTitle') AS buyCarDealTitle,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarDealValue') AS buyCarDealValue,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.buyCarOptions.Metallic lak') AS metallic_lak,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInLicensePlate') AS tradeInLicensePlate,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInMileage') AS tradeInMileage,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInAppraisal') AS tradeInAppraisal,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInMake') AS tradeInMake,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInFuel') AS tradeInFuel,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInModel') AS tradeInModel,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInTrim') AS tradeInTrim,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInTransmission') AS tradeInTransmission,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInBuildYear') AS tradeInBuildYear,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.initials') AS initials,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.firstName') AS firstName,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.infix') AS infix,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.lastName') AS lastName,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.phone') AS phone,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.email') AS email,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.postalCode') AS postalCode,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.houseNumber') AS houseNumber,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.houseNumberAddition') AS houseNumberAddition,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.street') AS street,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.city') AS city,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.terms') AS terms,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.content') AS content,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerId') AS dealerId,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerName') AS dealerName,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerCountry') AS dealerCountry,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerZipcode') AS dealerZipcode,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerStreet') AS dealerStreet,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerCity') AS dealerCity,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerPhoneNumber') AS dealerPhoneNumber,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerEmail') AS dealerEmail,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerLogo') AS dealerLogo,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.dealerLocationsUrl') AS dealerLocationsUrl,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.externalId') AS externalId,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInTradeWorth') AS tradeInTradeWorth,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInSellWorth') AS tradeInSellWorth,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInTradeInWorth') AS tradeInTradeInWorth,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInNewWorth') AS tradeInNewWorth,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInOffer') AS tradeInOffer,
    JSON_VALUE(PAYLOAD, '$.submission.input_fields.tradeInOptions') AS tradeInOptions,
    JSON_VALUE(PAYLOAD, '$.submission.instance_token') AS instance_token,
    JSON_VALUE(PAYLOAD, '$.submission.reminder_mail_send') AS reminder_mail_send,
    JSON_VALUE(PAYLOAD, '$.submission.image_folder') AS image_folder,
    JSON_VALUE(PAYLOAD, '$.submission.taxation_date') AS taxation_date,
    JSON_VALUE(PAYLOAD, '$.submission.created_at') AS created_at,
    JSON_VALUE(PAYLOAD, '$.submission.updated_at') AS updated_at,
    JSON_QUERY_ARRAY(PAYLOAD, '$.submission.statuses') AS statuses
  FROM
  ${ref("TaxatieModuleOnlineDataProducer_lasttransaction")})
SELECT
  account,
  pk_crm_id,
  submission_id,
  submission_id_in_submission,
  taxation_module_id,
  leadSource,
  leadType,
  buyCarBrand,
  buyCarModel,
  buyCarType,
  buyCarEngine,
  buyCarPriceList,
  buyCarTestDrive,
  buyCarBrochure,
  buyCarPrice,
  buyCarImage,
  buyCarTaxationMailHeaderImage,
  buyCarTaxationPdfHeaderImage,
  buyCarExtraTradeInValue,
  buyCarDealTitle,
  buyCarDealValue,
  metallic_lak,
  tradeInLicensePlate,
  tradeInMileage,
  tradeInAppraisal,
  tradeInMake,
  tradeInFuel,
  tradeInModel,
  tradeInTrim,
  tradeInTransmission,
  tradeInBuildYear,
  initials,
  firstName,
  infix,
  lastName,
  phone,
  email,
  postalCode,
  houseNumber,
  houseNumberAddition,
  street,
  city,
  terms,
  content,
  dealerId,
  dealerName,
  dealerCountry,
  dealerZipcode,
  dealerStreet,
  dealerCity,
  dealerPhoneNumber,
  dealerEmail,
  dealerLogo,
  dealerLocationsUrl,
  externalId,
  tradeInTradeWorth,
  tradeInSellWorth,
  tradeInTradeInWorth,
  tradeInNewWorth,
  tradeInOffer,
  tradeInOptions,
  instance_token,
  reminder_mail_send,
  image_folder,
  taxation_date,
  created_at,
  updated_at,
  JSON_VALUE(statuses_new, '$.id') AS status_id,
  JSON_VALUE(statuses_new, '$.submission_id') AS status_submission_id,
  JSON_VALUE(statuses_new, '$.status') AS status_status,
  JSON_VALUE(statuses_new, '$.created_at') AS status_created_at,
  JSON_VALUE(statuses_new, '$.updated_at') AS status_updated_at
FROM (
  SELECT
    account,
    pk_crm_id,
    submission_id,
    submission_id_in_submission,
    taxation_module_id,
    leadSource,
    leadType,
    buyCarBrand,
    buyCarModel,
    buyCarType,
    buyCarEngine,
    buyCarPriceList,
    buyCarTestDrive,
    buyCarBrochure,
    buyCarPrice,
    buyCarImage,
    buyCarTaxationMailHeaderImage,
    buyCarTaxationPdfHeaderImage,
    buyCarExtraTradeInValue,
    buyCarDealTitle,
    buyCarDealValue,
    metallic_lak,
    tradeInLicensePlate,
    tradeInMileage,
    tradeInAppraisal,
    tradeInMake,
    tradeInFuel,
    tradeInModel,
    tradeInTrim,
    tradeInTransmission,
    tradeInBuildYear,
    initials,
    firstName,
    infix,
    lastName,
    phone,
    email,
    postalCode,
    houseNumber,
    houseNumberAddition,
    street,
    city,
    terms,
    content,
    dealerId,
    dealerName,
    dealerCountry,
    dealerZipcode,
    dealerStreet,
    dealerCity,
    dealerPhoneNumber,
    dealerEmail,
    dealerLogo,
    dealerLocationsUrl,
    externalId,
    tradeInTradeWorth,
    tradeInSellWorth,
    tradeInTradeInWorth,
    tradeInNewWorth,
    tradeInOffer,
    tradeInOptions,
    instance_token,
    reminder_mail_send,
    image_folder,
    taxation_date,
    created_at,
    updated_at,
    statuses_new,
  FROM
    sequences
  CROSS JOIN
    UNNEST(statuses) AS statuses_new
    )

`
let refs = pk.getRefs()
module.exports = {query, refs}
