name: Publish package to GitHub Packages
on:
  pull_request_review:
    types: [submitted]
jobs:
  build:
    if: github.event.review.state == 'approved' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # nodig om versienummer goed te berekenen met git
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@PowerkrautStijn'
      - run: npm ci

      - name: Set version from release label
        id: versioning
        run: |
          LABELS=$(gh release view ${{ github.event.release.tag_name }} --json labels -q ".labels[].name")
            
          if echo "$LABELS" | grep -q "Major"; then
          npm version major
          echo "🔼 Applied major version bump"
          elif echo "$LABELS" | grep -q "Minor"; then
          npm version minor
          echo "🔼 Applied minor version bump"
          elif echo "$LABELS" | grep -q "Patch"; then
          npm version patch
          echo "🔼 Applied patch version bump"
          else
          echo "❌ No valid version label (major/minor/patch) found. Exiting."
          exit 1
          fi

      - name: Commit updated version
        run: |
          git config user.name "PowerkrautStijn"
          git config user.email "stijn@powerkraut.nl"
          git commit -am "chore: bump version based on release label"
          git push origin HEAD:${{ github.ref_name }}

      - run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
